### ISSUE TITLE
proxy.ini少了几个参数是使用了动态调整吗

### ISSUE THREAD

**Issue by wpyok500** [XX-net/XX-Net-dev#10]
proxy.ini少了几个参数是使用了动态调整吗
[autorange]节点少了
waitsize = 
bufsize = 

没了这连个参数，还可以在manual.ini中调整这两个参数吗

**Comment by xxnet** [comment]
是写死了参数了。
相当于：
waitsize = 0
bufsize = 65535

感觉参数觉得没有必要动态调整，就直接写在代码中了。

**Comment by wpyok500** [comment]
![image](https://cloud.githubusercontent.com/assets/14154547/15204339/e0ca0afc-183e-11e6-87d0-735e3f28b028.png)

**Comment by xxnet** [comment]
不是这里

**Comment by jzp820927** [comment]
既然参数 硬编码了，自然有其代理，就不用再纠结修改了吧

**Comment by wpyok500** [comment]
![image](https://cloud.githubusercontent.com/assets/14154547/15219377/14c05382-1896-11e6-8535-07eefba377c5.png)
