### ISSUE TITLE
360卫士与OpenSSL模块

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net-dev#11]
可能火星了，群里朋友发的截图，360卫士弹窗，试图“修复”OpenSSL组件中存在的错误。据用户称，弹窗发生在安装XX并正常使用几天后。

![360试图“修复”openssl组件错误](https://cloud.githubusercontent.com/assets/6830787/15709766/111d3152-2839-11e6-8234-259f3d1b2f0f.PNG)

联想到之前，一些用户的反馈中反复提到360与OpenSSL模块之间的故事：

https://github.com/XX-net/XX-Net/issues/714

https://github.com/XX-net/XX-Net/issues/1197

三个案例均不相同，但都与OpenSSL模块相关。不知道是巧合，还是另有原因？XX对自身核心文件进行完整性校验，也许是有必要增加的功能。

**Comment by yeahwu** [comment]
报毒这个事情还是要抱着平常心，
俺编译的lantern大家都说加了病毒，俺就一句话，爱用用，不用滚
问题出在哪里呢？明显是要提高墙内朋友的知识水平嘛！
让他们知道什么叫开源？什么叫闭源？什么叫流氓软件？一切也就迎刃而解了。
不是xx的问题，是认知问题呀！
xx有毒，lantern有毒，goagent有毒，都tm听多了

**Comment by simonasd** [comment]
@yeahwu 我担心的不是xx有毒，而是被投毒
