### ISSUE TITLE
Pac采用黑名单还是白名单更好？

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net-dev#12]
看到 https://github.com/XX-net/XX-Net/issues/3628 ，决定发起一个讨论：XX-Net将来采用黑名单还是白名单呢？

个人的看法：

1. 被墙网站难以收录完全，小网站繁多；境内域名收录完整更容易，小网站多为.cn域名
2. 一些没有被墙的网站，直连缓慢，而代理之后明显加速
3. 可以直连的网站走代理，负面影响也就是速度慢、暴露APPID而已（网络大炮应该不会对这类人烟稀少的网站下毒），影响较小
4. 应该走代理的网站走了直连，不仅影响体验（网站打不开），而且会向网络接入的提供者泄漏用户的翻墙行为等信息。

**Comment by jzp820927** [comment]
我觉得最容易维护的应该就是，基于 国内路由表的IP匹配模式的白名单 PAC，基本上都不会维护，主要就是看匹配性能了。还有，我觉得白名单，和黑名单可以同时存在，由用户自己选择用哪种模式的PAC

**Comment by xxnet** [comment]
​我觉得黑名单、白名单可以同时存在，关键是要有一个高效率的规则。

假设白名单是直连，黑名单是需要走代理。
那么收到请求，
先检查白名单，如果存在，那么直连。否则跳到下面：
检查黑名单，存在，那么走代理。否则跳到下面：
未知情况，尝试DNS解析，然后直连，如果10秒无法获取DNS或者建立连接，那么走代理。
  记录下域名应该走的路径，提高下次访问的速度。

界面上提供一个修改的UI，用户可以添加或修改某个域名的路径。

对外可以提供一个PAC接口，也可以提供Http代理接口，给不支持PAC的客户端使用。

这个思路，大家觉得怎样？

**Comment by jzp820927** [comment]
可以，考虑很周全

**Comment by xxnet** [comment]
​这可以算是最开始的方案。

进一步的方案，可以在外网服务器上部署一个DNS解析代理，提供http接口，这样客户端可以透过GAE进行DNS解析。
只要GAE通的，就能够获得DNS解析，解决DNS污染问题。

这个步骤可以在未知的情况下调用。

**Comment by jzp820927** [comment]
通过 http 通道，解析 DNS，这个有创意

**Comment by simonasd** [comment]
于是又回到了之前的讨论：搞一个优秀的代理管理模块
