### ISSUE TITLE
来个讨论贴

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net-dev#13]
想把youtube改为直连，可解决youtube不能上传问题
然后windows启动代码还是改为以前的，可解决win10菜单不能切换问题，可能会导致老旧系统无法启动
然后还有什么大家唠唠
@xxnet  @yfdyh000  @Cat7373  @cc941201

**Comment by Cat7373** [comment]
有个不算问题的问题- -
我把系统时间改到一两天以后，然后由于时间不正确，HTTPS 连接会直接失败，然后大量失败之后 XX-Net 就会进入屏蔽状态，然后这时候把系统时间改回去就会看到，剩余十几万秒后解除屏蔽。。。

**Comment by yeahwu** [comment]
好久不见，妹纸想死俺了

**Comment by cc941201** [comment]
当时把YouTube改为gae是因为http2下direct会挂吧，现在改回去不会遇到同样的问题吗？解决这个问题估计需要更细粒度的控制，比如区分http1/2、区分下载上传

**Comment by yeahwu** [comment]
因为使用过程中发现都是gvs ip，也就是都是h1，h2很少
改为直连，youtube上下载不会出问题，
最好的方案是，至少保持连接池中有一两个h1

**Comment by Cat7373** [comment]
https://github.com/blog/2191-pin-repositories-to-your-github-profile

**Comment by yeahwu** [comment]
@cc941201 你的更新问题不解决一下？亲

**Comment by cc941201** [comment]
@yeahwu 更新问题怎么成我的了。。现在在墙外，回去再看看。很久没在Win上写过东西了

**Comment by Cat7373** [comment]
XX-Net 跟迅雷兼容性还真不是很好。
刚刚开着迅雷，XX-Net 打不开任何网页。
我的默认浏览器是 Chrome，然而点图标是用 IE 打开的状态页。
用 Chrome 打开状态页还会提示浏览器代理设置: Fail
重启 XX-Net 后才正常。

**Comment by Cat7373** [comment]
找到问题了，我的迅雷设置的使用 XX-Net 做代理，一直忘了改回来。
然而还是不理解为何点击图标状态页会变成 IE 打开，
以及 Chrome 打开状态页会提示浏览器代理设置: Fail。

**Comment by simonasd** [comment]
说到直连，Google搜索的验证码问题应该也是相关的。
