### ISSUE TITLE
讨论贴 第二季

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net-dev#14]
大家来吹吹牛逼呀！关于下一步怎么走？
要解决的问题？
要改进的地方？
然而xx又不在，只有靠大家来维护鸟！
俺是给大家打杂滴！
@yfdyh000 @Cat7373 @xxnet @cc941201 @zjhzxhz @Yonsm @teN-XX @linhua55 @xyuanmu @Kisesy @simonasd @jzp820927

**Comment by zjhzxhz** [comment]
新的特性暂时想不出来。
但是值得改进的地方倒是很多：比如对于用户来说不友好，上手太困难。
用户根本不知道Google Account，Google App Engine什么的。需要有一个向导。
之前 @think2011 提出过这个~ 然后就没有然后了（那个Issue找不到了）。

其他的问题，容我再想想。

话说我看到一个项目管理工具-[Trello](https://trello.com/)，虽然不一定有用。

**Comment by yeahwu** [comment]
向导，这个想法不错。直接丢一句“自己去看wiki”确实不太礼貌
加上俺们的wiki简直太厚

**Comment by zjhzxhz** [comment]
而且Wiki写的真的很烂呢~！（主要是我们迭代太快了）
我刚才在想，如果让我重新设计，可能不会把它设计成网页。客户端会更加友好吧。
但是这工作量太大了。其实有个浏览器的UI也还不错啦。

**Comment by yeahwu** [comment]
这孩子，瞎说什么大实话！

**Comment by think2011** [comment]
@zjhzxhz 后来工作变动一堆事情.. 我就忘了.... 现在也还是忙..

**Comment by think2011** [comment]
抱歉 ：（

**Comment by yeahwu** [comment]
发现问题一枚，大家改改，ipv6
https://github.com/XX-net/XX-Net/issues/3766

**Comment by zjhzxhz** [comment]
学校的IP v6瘫痪了 表示没法测试呢~
学校的网络中心比较傲娇~
@yeahwu

**Comment by yj1** [comment]
![default](https://cloud.githubusercontent.com/assets/19296995/16520639/fdb5cf96-3fc3-11e6-9819-29748dfae9f1.PNG)
![1](https://cloud.githubusercontent.com/assets/19296995/16520641/00b84a66-3fc4-11e6-8278-a93dc37e581e.PNG)

**Comment by zking77** [comment]
想出一份力，但是菜鸟一只，只能围观了，哎！

**Comment by xxnet** [comment]
​支持支持，建议先讨论现有问题，然后再看哪些问题进入开发，慢慢建立todo list，以及开发计划

**Comment by simonasd** [comment]
嗯，可以在XX-Net-dev的Wiki里面弄一个规划，大家讨论修改，然后感兴趣的童鞋可以认领相应的部分。

**Comment by CongZeng** [comment]
现在都用什么翻墙

**Comment by zjhzxhz** [comment]
@simonasd 所以可以试着用一些项目管理工具, 比如[Trello](https://trello.com/)

**Comment by yeahwu** [comment]
@xxnet 发起一个任务，鉴于已经有x-tunnel了。感觉可以把xx-net中的php模式剔除掉了，相关文件，代码谁给删除掉？
谁把这任务给领了？

**Comment by Cat7373** [comment]
删了不太好吧。。。
或者开个新分支，单独丢内个分支里。。

**Comment by yeahwu** [comment]
php模式真的很鸡肋，说用也能用，就是速度影响xx-net的形象。而且实在是也有1年没维护了，放在里面总感觉不舒服。加上冷不丁还有人在issues里问php问题，干脆扔掉算了。

**Comment by zjhzxhz** [comment]
我也觉得删了不太好. 但是的确没有用.
但也的确有人在用.

**Comment by yeahwu** [comment]
@Cat7373 妹子，把这个办了吧！办好了，俺以身相许。:smile:

**Comment by yeahwu** [comment]
@zjhzxhz 哈哈，又从v2ex过来了。正因为没啥用，才感觉丢掉算了，在用的，可以让他转移到gae，或者x-tunnel嘛

**Comment by xxnet** [comment]
​赞成删除PHP 模块

**Comment by yeahwu** [comment]
感觉自己有点强迫症，看到php就感觉好多余！x大见谅

**Comment by zjhzxhz** [comment]
@yeahwu

我的强迫症更严重😝

**Comment by yeahwu** [comment]
刚从V2EX撕逼回来，好累！
那你来把这事办了呗，说不定俺一言不合就以身相许了。:trollface:

**Comment by yeahwu** [comment]
有没有发现github的字体有变化？

**Comment by jzp820927** [comment]
没有

**Comment by Cat7373** [comment]
发现了- -
不是很喜欢新字体- -

**Comment by yeahwu** [comment]
@Cat7373 妹子说好的以身相许，:trollface:

**Comment by simonasd** [comment]
哪里字体变了，没有看出来= =
