### ISSUE TITLE
(3/3) 加入开发者模式开关

### ISSUE THREAD

**Issue by cc941201** [XX-net/XX-Net-dev#15]
1. 开发者模式下不会自动删除根目录下`launcher`文件夹，确保提交commit时不会误删。
2. 不开开发者模式时会减少日志，只显示WARN、ERROR和FATAL级别的消息，解决之前有人反应的消息太多污染系统日志池的问题。这个可以调用`xlog.py`中的`setLevel`来实现。
3. 据@yeahwu建议，开发者模式下可以显示本源的链接：https://github.com/XX-net/XX-Net-dev/issues 很多开发者还不知道有这个源。

**Comment by yeahwu** [comment]
这个想法很好，普通用户确实不需要接收太多日志。还可以接收更多开发者参与进来！

**Comment by cc941201** [comment]
是否需要加入修改自动升级源的功能来测试自动升级？
<img width="606" alt="2016-07-10 14 01 10" src="https://cloud.githubusercontent.com/assets/3082401/16711929/01381b9e-46a7-11e6-8b74-20a086f84341.png">

**Comment by yeahwu** [comment]
@cc941201 自动升级测试确实很麻烦。然后为什么不把“开发者”放在下面侧栏位置？“关于”上下都可以，醒目点嘛！
![2016-07-10](https://cloud.githubusercontent.com/assets/13328328/16712058/8e1b8c5e-46ab-11e6-9d47-6cd402c4ae29.png)

**Comment by cc941201** [comment]
感觉内容比较少，单独放空白太多，页面如何布局比较好？

**Comment by yeahwu** [comment]
启用开发者
自动升级测试
开发者论坛
三行也可以了。不知道你那启用开发者，有没有加入日志开放级？

**Comment by cc941201** [comment]
还在界面设计阶段，没开始写代码。设想是开发者模式直接开全部日志，还需要加日志级别单选框吗？感觉DEBUG和INFO在代码里混着用比较多，没有统一标准。

**Comment by yeahwu** [comment]
开发者模式，全部开。

**Comment by jzp820927** [comment]
这个可以有，支持

**Comment by simonasd** [comment]
日志太庞杂的问题一直想提，没想到这边提出来了

**Comment by xxnet** [comment]
日志，可以把已经稳定下来了，不关键的部分去掉。
   只留下有价值的部分，就会少很多。

launcher 目录，已经删除了，不再兼容之前的版本。
