### ISSUE TITLE
(1/3) 开启2.X自动升级

### ISSUE THREAD

**Issue by cc941201** [XX-net/XX-Net-dev#17]
首先介绍一下目前自动升级情况：
1. 2.X版本依靠读取根目录下`README.md`中的版本信息和网址自动升级。因出的问题较多，X大将`README.md`中下载网址移至`download.md`关闭了2.X的自动升级。
2. 3.X的自动升级机制较为复杂。通过校验哈希值、并将文件解压到新文件夹而非直接覆盖，解决了大部分升级失败的情况。
3. 由于XX-Net的易用性，很多用户并不了解项目的发展，依然停留在2.X。就算懂英文会提交issue的用户中也有相当一部分停留在2.X不知道如何升级。

从2.X自动升级至3.X的代码已经完成很久了，存于`launcher`目录中，原理是替换旧版的`update_from_github.py`，之后利用新版的自动升级代码再次升级，以保证压缩包哈希值正确。

开启2.X自动升级剩下的唯一步骤就是在`README.md`中填入版本信息和网址。

但`launcher`中代码没有经过严格测试。我可以整理一下需要测试的版本（主要是`update_from_github.py`有变化的2.X版本），并测试macOS下的自动升级。但Linux和Windows下的测试需要大家帮助。

**Comment by yeahwu** [comment]
这个俺保留意见，其实俺的观点比较极端，舍弃2.0版本的用户。

**Comment by cc941201** [comment]
但我们只有一步之遥就能把2.X版本用户转为3.X用户，只需要做一些简单的测试

**Comment by jzp820927** [comment]
干脆搞个 民投 算了，看支持 2升级3，和舍弃 2升级3，哪个占比大。

**Comment by cc941201** [comment]
觉得支持2升3并没有什么坏处，只是优先级的问题，是否需要解决别的更紧迫的问题

**Comment by yeahwu** [comment]
主要是被升级搞怕了，搞定了3.0感觉已经很不容易了。然后升级代码也能简洁点。

**Comment by cc941201** [comment]
X大当时也是这样想的。现在2升3代码已经完成很久了，在`launcher`目录里，唯一要做的就是测试。

**Comment by xxnet** [comment]
恩，先想好怎么测试，测试好了，就可以放开试试，比如先放开测试版的升级，稳定了，再放开稳定版的升级。

先把需要测试的要点罗列出来，然后想对应的测试方法。

**Comment by xxnet** [comment]
这么久过去了，应该没有多少2.X了吧
