### ISSUE TITLE
关于Python 3的讨论

### ISSUE THREAD

**Issue by hzxie** [XX-net/XX-Net-dev#19]
关于这一点 我觉得可以引入 `__future__`来慢慢迁移到Python 3.
因为毕竟2个分支要同步真的还蛮麻烦的.

**Comment by jzp820927** [comment]
真应该慢慢迁移到 py3了，不然 py3 分支就废了。

**Comment by yeahwu** [comment]
是的，俺都忘了还有个py3分支了

**Comment by zjhzxhz** [comment]
但是考虑到Py3分支和Py2分支的同步问题, 建议引入`__future__`, 这样到时候可以无缝切换到Python 3.
应该是这样的吧~

**Comment by xxnet** [comment]
折腾了一段时间的py3之后，感觉是这样：
1. 写py3 稍微麻烦，需要更多的显式类型转意，似乎背离了python易用傻瓜的特性
2. 整个python社区，对py3的热情不高，很多库（比如GAE）就不支持py3
3. py3 的性能，有的场景快，有的场景慢，而原来期望提升大量线程下的性能，目前并没有存在强烈需求。 
   目前xx-net 有50-100个线程在后台跑，但对PC的来说完全感觉不到性能问题。
4. python-for-android 项目，对py3的支持也还没有成为主流，默认的项目还是py2，官方说py3可能会遇到问题，说明py3支持还没有成熟。
5. fqrouter项目是自己移植py3到android上的，py3是否有优势，无从得知，原作者已经匿了。

从实用角度出发，建议暂停py3的跟进，在有更有力的理由之后，再推进py3分支的开发。
