### ISSUE TITLE
[转发]解析Http请求的Bug

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net-dev#20]
解析Http请求的Bug：

https://github.com/XX-net/XX-Net/issues/4694

**Comment by jzp820927** [comment]
这么跑这边来发 issues 了，项目都基本上没怎么维护了。

**Comment by simonasd** [comment]
@jzp820927 也就是登记备案一下，指不定哪天就有人介入了。

**Comment by jzp820927** [comment]
好吧，我能说其实我也希望是这个结果嘛。

**Comment by simonasd** [comment]
@jzp820927 不必悲观，不必心急，要对社区有希望和耐心。我觉得，尽自己一份力就好，像P大所说，至少在将来膝下儿孙满堂之时，能聊聊自己在旧社会的抗争史。

再说了，开发活跃的下降也部分因为XX-Net达到了一定的成熟度嘛。

**Comment by jzp820927** [comment]
现在 issues 就我一个人天天在这儿回答问题，可悲啊！

**Comment by yeahwu** [comment]
最近比较忙，出来冒个泡。
天朝屁民 <notifications@github.com>于2016年12月20日 周二22:02写道：

**Comment by jzp820927** [comment]
好吧，就我是闲人。

**Comment by simonasd** [comment]
@jzp820927 Google code关张，实在可惜，那是一个时代啊。现在高压之下，热心人和用户都分散到各个项目去了，很难再形成当年的规模了。不过化整为零，各自为战，也不失为一种渡过苦难的办法。

**Comment by jzp820927** [comment]
只能这样想了

**Comment by xxnet** [comment]
圣诞快乐！
祝各位约会成功！
