### ISSUE TITLE
【Bug】建议增加如每隔两个小时自动检查所有IP这种功能

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net-dev#21]
基本每次都会显示有3000个有效IP，但是运行检查所有IP之后就只有不到2000个有效IP，那么多无效IP掺杂着严重拖慢通过xx-net访问网站的速度。
所以建议增加如每隔两个小时自动检查所有IP这种功能。

**Comment by yfdyh000** [comment]
间歇性阻断和干扰，所以有可能你检查OK的IP下次就连不上了，检查失败的IP下次就连上了。所以可能没用。

**Comment by redstoneleo** [comment]
@yfdyh000 GFW会间歇性阻断和干扰？

**Comment by yfdyh000** [comment]
据说，443端口丢包劣化。可以去 https://github.com/phuslu/goproxy/issues 看看。

**Comment by jzp820927** [comment]
11 月初就开始了，随机丢包，不固定封 IP 了现在
