### ISSUE TITLE
GoProxy备份

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#24]
[README](https://github.com/dou4cc/goproxy/blob/master/README.md) | [Issues](https://raw.githubusercontent.com/dou4cc/resource/master/goproxy-issues.7z) | [Releases](https://github.com/phuslu/goproxy-ci/releases/)

**Comment by xxnet** [comment]
https://goproxy0.github.io/discuss_history/seo.html
任务完成了，辛苦dou4cc
