### ISSUE TITLE
解决了存在一年的GAE_proxy若干稳定性bug

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#27]
刚刚提交了代码。

解决最大的bug：
在网络异常时，会把请求在处理时丢失，导致请求端一直等不到返回，连接没有断开，也不会重试。

其次是性能上的优化，在请求量大时，能够自动建立更多的链接，而在请求量小时，会自动降低资源消耗。

**Comment by jzp820927** [comment]
真难得，这么久了，X大还能来更新。

**Comment by wooowooo** [comment]
放鞭炮庆祝xxnet大侠重出江湖

**Comment by yeahwu** [comment]
好久不见，难得。
wooowooo <notifications@github.com>于2017年9月1日 周五10:33写道：

**Comment by xxnet** [comment]
好久不见，哈哈
