### ISSUE TITLE
3.1.1 版待发布

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#3]
https://github.com/XX-net/XX-Net/releases/tag/3.1.1

修复：
    appid out quota error process
    fix beep on windows
    ip not removed if not support gae

**Comment by CongZeng** [comment]
嘟嘟嘟声音没了，目前很流畅谢谢

**Comment by xxnet** [comment]
好，​再等一个小时，就发布为测试版

**Comment by jzp820927** [comment]
终于有一个完美的 3.xx 大版本了

**Comment by yeahwu** [comment]
3.12版表示ip稳步上升中。很棒，兄弟，辛苦了！

**Comment by xxnet** [comment]
​有效果就好开心，http/2 这个大坑终于搞定，俺现在算http/2
专家了，目前除了Chrome之类的浏览器之外，大部分库都还没有很好支持http/2，包括OpenSSL，Linux的版本还没有支持的很好，所以现在Linux/Mac下都表现不如Windows版本。

**Comment by jzp820927** [comment]
意思是说，win 还走在时代前列了，Linux 还落后了，不能用 http2 ？

**Comment by xxnet** [comment]
不是，就是比较麻烦。

先试试把系统的python-openssl 库删了，会自动启用内置的，如果缺什么包，再另外安装。
目前cffi 库和libc 的版本的强依赖的，需要根据系统libc来安装

**Comment by jzp820927** [comment]
能不能大概说说，http2 ，必须哪些依赖，最低版本要多少？我用的是最新的  ubuntu 16.04，内置的库和包应该都比较新，但是不知道能不能支持？

**Comment by xxnet** [comment]
​你看看状态页，有Openssl 是否支持的信息

**Comment by jzp820927** [comment]
哦，原来状态页可以看，那行，我自己确认下。
