### ISSUE TITLE
[TODO] GAE IP段整理

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#30]
GAE 的IP段需要维护下，暂时的思路如下：
1. 收集网上所有可能的GAE ip段数据，汇总。

2. 所有ip 段先转换为 /24 的格式。
   比如 27.80.250.0-27.80.250.255

3. 对上面每一个小段进行扫描
  要放到墙外进行。
  这一步是验证这个段到底有没有存在可用的ip。
  如果没有，这个小段就删除掉。
  只要有一个，就留下来。

4. 把扫描结果合并

我暂时还在优化x-tunnel，需要2-3天时间，有没有人来？

**Comment by dou4cc** [comment]
不大可能有时间参与，因为我不会python，现学速度很渣。

--------
- 没有国内跳板，上外网随便就能限速。
- 即使cloudflare没被封锁，限速也是常有的事。
- 国内跳板的收集可能比google ip的收集更重要。
- x-tunnel服务端换成免费paas也许能省钱。
- 我当前的翻墙方案：https://raw.githubusercontent.com/dou4cc/resource/master/fq.7z.zip

**Comment by dou4cc** [comment]
400万ip的ip段：https://github.com/phuslu/goproxy/issues/1935

**Comment by xxnet** [comment]
cloudflare 被限速，不会比GAE被封严重吧。
已经把之前GAE的大部分算法搬过来了，暂时不太担心。
还有很多云可以做前端，不过是需要花些精力而已。

免费paas都是有限制的，大规模的没有被封的，用户使用起来方便的，具体有什么建议？
我们要非技术用户能够使用的方案，少数技术用户才能用的方案，做出来价值也不大。

**Comment by dou4cc** [comment]
别用任何云，要么全是审查，要么随时限速。
国内跳板主要有http反代、sniproxy、socks/socks5代理。
heroku免费，可以注册多个账号突破免费套餐的限制。

**Comment by dou4cc** [comment]
cloudflare和gae哪个被封得更厉害其实取决于你。
滥用heroku不知道那边能不能受得了，道德上应该没有错。

**Comment by dou4cc** [comment]
gae支持自定义域名了：https://github.com/phuslu/goproxy/issues/2030

**Comment by dou4cc** [comment]
如果sniproxy和heroku中间插一个gae自定义域名，不知道能不能减小gfw封锁heroku的动机：https://github.com/phuslu/goproxy/issues/2033

**Comment by SeaHOH** [comment]
直接全网扫一遍不就行了？几天就搞定了吧。
如果要更准确，可以用几个不同位置的 vps 各扫一遍。

**Comment by dou4cc** [comment]
是啊，你在国外，不会出现沦陷区扫着扫着连国内网站都变慢的事情。

**Comment by SeaHOH** [comment]
>对上面每一个小段进行扫描
要放到墙外进行。
这一步是验证这个段到底有没有存在可用的ip。
如果没有，这个小段就删除掉。
只要有一个，就留下来。

这是 @xxnet 提的要求

**Comment by dou4cc** [comment]
@SeaHOH 墙外扫排除不可用ip，墙内扫验证可用性，X大没说墙内就不扫了。

**Comment by SeaHOH** [comment]
>如果没有，这个小段就删除掉。
只要有一个，就留下来。

我老是不能理解你的思路……

**Comment by dou4cc** [comment]
@SeaHOH X大可能想开超高的线程数，这样存在漏扫，所以要尽可能保留ip段（滑稽

**Comment by SeaHOH** [comment]
非要人加 @ 才知道是对谁讲吗，你真的有点麻烦。

这句话等会儿会删掉，我真不喜欢这样讲话。

**Comment by pgz123** [comment]
@SeaHOH/dou4cc是中学生

**Comment by dou4cc** [comment]
@pgz123 我换头像了（得等缓存过期），你能不能别把我当梗？之前gop issues区那个发GoogleIPHunter的博客都是中文，发issue就换英文，对ta的匿名性没有帮助（如果ta想匿名）。

**Comment by xxnet** [comment]
​ 这个思路是有这样的考虑：
1、有些ip段是没用，应该剔除掉，提高扫描的成功率
    这样大量合并可能的ip才不会出现降低扫描速度。

2、有些ip，虽然只收录了几个ip，但是很可能会有调整，做过运维管理的人就可以理解。

**Comment by SeaHOH** [comment]
直接全网扫不就省事了嘛，不用找 IP 段了。

**Comment by SeaHOH** [comment]
直接重第三步开始

**Comment by dou4cc** [comment]
@xxnet google的人不会没事找事只卖零星ip，要买都是一个段

**Comment by SeaHOH** [comment]
拥有但不等于都会用于某个用途，所以才要挑选。

**Comment by onplus** [comment]
墙外直接暴力扫全网？
```
1.0.0.1-9.255.255.255
11.0.0.1-100.63.255.255
100.128.0.1-126.255.255.255
128.0.0.1-169.253.255.255
169.255.0.1-172.15.255.255
172.32.0.1-191.255.255.255
192.0.1.1-192.0.1.255
192.0.3.1-192.88.98.255
192.88.100.1-192.167.255.255
192.169.0.1-198.17.255.255
198.20.0.1-198.51.99.255
198.51.101.1-203.0.112.255
203.0.114.1-223.255.255.255
```

**Comment by SeaHOH** [comment]
方便啊，以前有人干过。

**Comment by xxnet** [comment]
暴力扫全网，思路不错，不知道要多久。

GGC 经常是和目标单位合作，比如和某个大学网络合作，在大学里放台缓存，
我记得有这样的报道。

所以这些ip的调度，不是一片的。

**Comment by SeaHOH** [comment]
记得那人说过是几天，不过我刚才算了下 1000 线程，超时 2 秒，都要 2 个月……
看来需要多用几个 vps

另外，谷歌的网络部署，这里有介绍，全是英文，没看太懂。
https://peering.google.com/#/infrastructure

**Comment by SeaHOH** [comment]
不对，应该发现一个后就可以确定，实际时间会短一点。

**Comment by candy2107** [comment]
我的思路是:
找一个有信用卡的人开GCE扫400万的ip段,筛选出有效ip

**Comment by candy2107** [comment]
我的思路是:
找一个有信用卡的人开GCE扫400万的ip段,筛选出有效ip
400万足够了

**Comment by MeABc** [comment]
X大有没有想过改变一下 xx-net 的扫描 IP 策略呢？纠结于 IP 库这个是没完没了的，IP 库没有足够的一天。假如谷哥官方放出1亿个，是不是我们也要放进去。。。

**Comment by candy2107** [comment]
@MeABc 
xxnet内置ip库上次更新是一年前,有不少ip段失效了,扫很久都扫不到ip,所以应该更新ip段了
400万里面筛选出有效的,估计只有几十万个,不算多了

**Comment by MeABc** [comment]
为了更具有发言权----没有使用/调查就没有发言权。
我下了 xx-net ，3.4.2，全默认，半小时结果图：

![image](https://user-images.githubusercontent.com/18194126/30513864-57ebfac8-9b3d-11e7-9720-cdaca3571be6.png)

**Comment by MeABc** [comment]
我想表达的意思是：
xx-net 的定位是什么，开箱即用（一运就可以使用），还是发挥长时间运行的优势（毕竟后台有扫描）。
如果放一个超大库，我的理解是应该是后者（发挥长时间运行的优势）。

**Comment by onplus** [comment]
一个月前解压即用，现在看当地ISP的心情

**Comment by MeABc** [comment]
个人认为当下另一重要任务应是完善文档和引导普通用户使用文档。
如楼上所做的， https://github.com/XX-net/XX-Net/pull/6420

**Comment by MeABc** [comment]
@xxnet 

> 所有 ip 段先转换为 /24 的格式。
比如 27.80.250.0-27.80.250.255

已转换好了。不过格式是这样子的 `27.80.250.0/24` （标准格式）。

原有的：
[ip_range.txt](https://github.com/XX-net/XX-Net-dev/files/1309047/ip_range.txt)

转换好的：
[ip_range_tmp.txt](https://github.com/XX-net/XX-Net-dev/files/1309048/ip_range_tmp.txt)

不算不知道：xx-net 原带的 ip 都有 140 万之多 （范围）。

**Comment by xxnet** [comment]
​干得好，这慢慢一步一步推进！
最好把转换的代码也发出来，因为前面收集ip范围的步骤，还会不断加入新的ip段。
其实收集ip范围，可以用gae_proxy
下面有一个generate_ip_range.py可以用，兼容常见的各种格式，只需要把收集到的段放在一个文件里作为输入。

后面扫描ip的部分，也是要开多线程扫描，可以参考gae_proxy里面的代码改改。
我这有墙外的服务器，调试好了，可以把代码给我，我放墙外跑。

**Comment by jzp820927** [comment]
支持一下 X 大

**Comment by SeaHOH** [comment]
给个输入输出类型，我把扫描部分做出来。
我这儿有现成的代码，改改就能用。

**Comment by xxnet** [comment]
输入/输出格式，用 27.80.250.0/24 就好。

输出最后再用generate_ip_range.py 合并就可以了

**Comment by SeaHOH** [comment]
好，明天我在这里发个附件。

**Comment by onplus** [comment]
有没有可能
加一个上传按钮，把用户扫出来的ip都收集起来

**Comment by jzp820927** [comment]
每个地方的可用 IP 都不一样，意义不大

**Comment by SeaHOH** [comment]
[scan_gae_range.zip](https://github.com/XX-net/XX-Net-dev/files/1309786/scan_gae_range.zip)
将每个 /24 段视为整体用一个线程处理，如果要将每个 IP 视为独立个体来处理，还需要增加许多代码才行。

主要在 Python3 下面测试过，已经可用。

**Comment by SeaHOH** [comment]
```py
class gae_scanner(threading.Thread):
    Lock = threading.Lock() #顺手写的，结果没用，忘了删……
```

**Comment by xxnet** [comment]
good job.

我到服务器上试试。

**Comment by SeaHOH** [comment]
哦，注意导入，用了 `openssl_wrap.py`。

还有线程是测试时的，非常小，需要修改，超时也可以调整。

日志啥的可以自己添加，我只打印了一个主要异常处理。

**Comment by SeaHOH** [comment]
用 `openssl_wrap.py` 好像有点多此一举，我去掉试试。

**Comment by SeaHOH** [comment]
算了，还是用 `openssl_wrap.py` 比较简单。

**Comment by xxnet** [comment]
​这个没有问题。
已经跑起来了，等结果。

**Comment by xxnet** [comment]
​开500线程，加了一点日志，显示还剩下多少个 /24，看上去很快了。
先跑目前内置的段，再把400万ip段拿来跑一次。
今晚就能完成。

**Comment by SeaHOH** [comment]
能用就好 :smiley_cat:

**Comment by xxnet** [comment]
​团队协作，很开心！

把ip范围缩小，然后把默认扫描线程改成10看看。
目前看扫描线程是容易被发现的。

在考虑要不要做一个模拟正常流量使用的模块，光有连接google 的流量，太容易被发现了。

**Comment by SeaHOH** [comment]
这个不是在国外用吗？国内用的话要改很多。

**Comment by dou4cc** [comment]
@xxnet 根据我的经验，近几天不管正常流量多不多，只要短连接多就很可能被限速。

**Comment by dou4cc** [comment]
@xxnet XX-Net的ip扫描确实应该改成被动的，即用户拿XX-Net上网时扫描的流量和其它流量一起发出，空闲时再以低线程数扫描，并和国内流量混在一起。

**Comment by xxnet** [comment]
​意思是XX-Net/GAE 模块的默认扫描ip线程数，改成10，甚至更低。
避免被墙识别出来，当然，第一次使用，会等待更长时间。


刚才第一轮扫描已经跑完了，出来2200个/24段，不到输入的一半。
现在开始跑400万的

**Comment by dou4cc** [comment]
@xxnet 首次运行时从ip段中按一定策略随机选一些出来作为good-ip.

**Comment by xxnet** [comment]
随机挑选ip，扫描ip就是这么做的。

感觉有必要扫描一下全网，到底有多少可用ip。（我们前面扫的是ip段，而不是具体的ip）
不仅仅要验证ip 的证书，还要判断是否可以作为GAE使用。
如果在这个已经验证过的ip池里，再进行扫描，概率会更高。

**Comment by xxnet** [comment]
​定期更新这个ip池就可以了。
提高概率，意味着更少的扫描线程，就可以扫描到ip，不容易暴露特征。

**Comment by MeABc** [comment]
这是我原始的转换代码。大部份来自 checkgoogleip 。
须说明一下，这个是“原始”的。只针对 `1.0.0.0-1.0.0.255` 这一种情况进行转换。
其它格式还没来的及整合。这个先放上来。python3 的。

[ip.zip](https://github.com/XX-net/XX-Net-dev/files/1310350/ip.zip)

**Comment by xxnet** [comment]
我们的想法一样，Great!

那么接下来就做一个全扫的工具：
 输入ip段，
 输出可用ip列表。
 要验证ip 可用作为GAE工作，验证方法可以用gae_proxy/check_ip.py 里的函数。


400万扫了一半了，有1600个有效段，那么估算有3200个有效/24段，确实多出来不少。

**Comment by xxnet** [comment]
​等做完了，把代码和数据都整理一下，建个项目放进去。
给以后要继续改进留下东西。

**Comment by xxnet** [comment]
​扫描结果出来了，3197个 /24 段，我来把这些段合并下，然后发布一个新版看看。

刚刚讨论的新思路，可以开一个新topic 继续推进

**Comment by xxnet** [comment]
​新版已经发布：
https://github.com/XX-net/XX-Net/releases/tag/3.5.5

**Comment by xxnet** [comment]
​代码整理好，放在
https://github.com/XX-net/XX-Net-dev/tree/master/scan_ip_range

**Comment by xxnet** [comment]
完美收工！

**Comment by Whero090402** [comment]
请问扫描IP过程中是否需要联网
