### ISSUE TITLE
翻墙软件支持代理UDP是当务之急

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#31]
https://twitter.com/UnsignedInt8/status/909009704789041152

**Comment by xxnet** [comment]
​BTC 是 TCP 的吧

**Comment by dou4cc** [comment]
好吧，居然是基于irc，还以为跟dht有关系：
![image](https://user-images.githubusercontent.com/7764678/30518306-b5c5ae86-9bac-11e7-9b77-96cec2a7437a.png)
