### ISSUE TITLE
关于python27文件夹

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net-dev#32]
发现`code/version/python27` 这个文件夹有30M ,每次更新都多占用那么多的空间. 更新几次后总体积就几百M了.

项目历史显示这个文件夹里的内容很少修改
1.这个文件夹可否移动走,比如移到root, 不要每次升级都多占用那么多空间
2.这个文件夹是通用的python库还是项目原创的代码? 如果是通用python库,可否删除一些以节省空间

**Comment by xxnet** [comment]
​这个有考虑过，之前是放在root里的，可是需要升级时就容易出问题。
里面大部分是标准库，只有少量自己写的。

其实问题也简单，升级后把原来的目录删除就好了。
简单的策略，可以在launch启动里，检查老的版本目录，删除。
（不考虑版本回退了，根据版本管理的思想，有问题，就发新版本，不回退。）

**Comment by onplus** [comment]
内置主要是为了winows系统吧？入门用户估计不会为了xxnet装python

**Comment by xxnet** [comment]
​是的，其他系统都默认有python
