### ISSUE TITLE
[TODO] 一份详细的X-Tunnel 使用说明

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#35]
问题：
新手分不清楚GAE_proxy和T-tunnel的关系。
以及如何配置浏览器代理。
如何设置。

wiki上有一份，但是不够清楚。
大家处理，完善一份文档出来。

**Comment by candy2107** [comment]
这个做的差不多了,可以关了吧

**Comment by candy2107** [comment]
建议加入邮箱验证,防止恶意刷流量

**Comment by xxnet** [comment]
谢谢各位。

过了测试阶段，就需要购买流量了，准备加入推荐机制，
推荐人和被推荐人，都会获得购买流量10-20%的奖励，有效期3年。
