### ISSUE TITLE
[TODO]QUIC支持

### ISSUE THREAD

**Issue by candy2107** [XX-net/XX-Net-dev#37]
前言 : quic属于新技术 , 且目前墙没有针对quic的策略 , 所以增加QUIC的支持是可行的
任务列表:
1.编译出python的quic库文件,可以用任意的语言实现
2.将quic库与xxnet对接
2.quic ip筛选策略
4.quic与tls混用的策略

**Comment by candy2107** [comment]
https://github.com/phuslu/goproxy/issues/2026#issuecomment-330434787

**Comment by xxnet** [comment]
先能够在python下建立连接，至于怎么智能调度连接池，这个可以参考原来的算法，复制一套新的出来或者在原来基础上建立作为一个新的类型，了解了特性设计。

**Comment by candy2107** [comment]
quic链接的特性和tls太不一样了
https://github.com/Kisesy/gscan_quic/issues/3#issuecomment-315545198
所以ip筛选算法可能要重新设计

**Comment by candy2107** [comment]
https://github.com/osdf/pyquic
这个提供了一个思路,但是库不完整
目前要做的是找个完整的库 c 或c++ 的都行
https://github.com/phuslu/goproxy/issues/1883
然后用python调用这些库
@xxnet 
对于quic库的选择,你有什么看法?

**Comment by SeaHOH** [comment]
精力不够啊，还要熟悉协议，人家搞都是很多人贡献的，我们这儿本地化文档支持完全不行。

**Comment by xxnet** [comment]
https://github.com/osdf/pyquic
 不完整，缺什么？能否先写个测试看看。

封python库还没有搞过，发现一个项目，也可以试试：
https://github.com/go-python/gopy
不知道自动化处理，会有什么成本

**Comment by candy2107** [comment]
完整的quic库包括crypto,openssl等额外的东西 , 还有h2-quic , 不只是一个quic.c
只加入 py_quic.pyx 不知道能否运行成功

**Comment by xxnet** [comment]
​crypto/openssl库，xxnet已经带了，可以试试，到底需要哪些东西

**Comment by candy2107** [comment]
QUIC is primarily designed to send and receive HTTP/2 frames and entire streams over UDP.
Webservers would need to have 3 completely different implementations of the HTTP stack (for HTTP/1.1, HTTP/2 and HTTP/QUIC), where only the most upper layer (interfaces for sending requests and respones) can be shared, the remaining stuff will be very different.

QUIC 需要http2

**Comment by SeaHOH** [comment]
QUIC 的 H2 是独立实现的。

**Comment by xxnet** [comment]
​h2 协议，python 有了，hyper库
xx-net还在上面基础上做了改进，可以同时走多个请求。

**Comment by xxnet** [comment]
感觉实现成本很高了，要封锁也是容易的。
先放着吧。

**Comment by candy2107** [comment]
目前采用的在墙外筛选ip,墙内小进程扫描解决了没有ip的问题
所以这个以后再做也不迟
