### ISSUE TITLE
[TODO] 升级先提示，确认后再更新

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#38]
目前状态：
  检测到有推送更新，立即下载更新。

问题：
  有时想用老版本，启动完就已经更新到最新版本了。

解决方案：
  默认之提示有新版，在Web页面的上方出来一个提示条，点击后进入升级页面。
  设置页面里，可以选择为自动升级，不需要提示。 

难度：
  中等
  需要python，html, js, css
  有可参考实现。

**Comment by dou4cc** [comment]
建议ip库和软体单独标注版本。
建议两者单独设置更新方式：
- 不更新
- 提示下载更新
- 自动下载，安装前提示更新
- 自动下载和安装更新

**Comment by onplus** [comment]
@dou4cc  ip段设成pac-gfwlist那样在线获取，支持手动获取。
就在这个页面加个获取按钮http://127.0.0.1:8085/?module=gae_proxy&menu=advanced

**Comment by SeaHOH** [comment]
UI 苦手……
你们先把 UI 框架搞出来，需要 js 和 py 的地方写上注释，标明详细需求，我可以从这儿做下去。

**Comment by onplus** [comment]
@SeaHOH 
应该只需要js获取ip段，填充到那个ip段列表里，然后点击“提交”就行了。没有新增py部分

**Comment by SeaHOH** [comment]
跟 IP 没关系吧，你是说 @dou4cc 单独更新 IP 的提议？不是已经有自行导入嘛。

**Comment by xxnet** [comment]
这个主题先不讨论ip库的更新，聚焦到代码更新上来吧。

UI的和python底层的，建议UI先搞一个开头，然后底层再配合一下就好，感觉工作量大的还是UI

**Comment by SeaHOH** [comment]
不会框架，写 html 基本都是临时翻 W3C……

**Comment by dou4cc** [comment]
我精通js、css熟练、html现查，不会任何框架，没参与过合作开发，没写过大项目。

**Comment by xxnet** [comment]
​我也一样，html都是现学现用。
顶部提醒拦，记得已经有了，可以参考，或者改改用。

弹窗，就算了。

**Comment by xxnet** [comment]
团队协作，就是各自会一点就好了，不会的现学。
python 我也是做这个项目才学的，之前写了很多代码都是格式错误低级，呵呵。

**Comment by wooowooo** [comment]
导入证书也应该是这种方式. 先提示导入, 点击提示条后再导入.
目前这种启动时自动导入, 与流氓软件就无区别了.

**Comment by dou4cc** [comment]
@wooowooo 建议不自动导入，毕竟firefox导入、证书更新还得手动。

**Comment by xxnet** [comment]
​恩，能够提示最好。
之前做成提示框，兼容性不好做，才做成自动导入证书的。


可以弹出一个Web页面来，点击导入，才真的执行导入。

**Comment by wooowooo** [comment]
就在状态页上方，以醒目颜色提示就可，与升级提示可共用一些代码。反正第一次运行的电脑会打开状态页的。

**Comment by xxnet** [comment]
@wooowooo  已经提交了显示tip的代码：
https://github.com/XX-net/XX-Net/pull/6572

接下来可以先把升级改成2个步骤:
1. 提醒有新版本
2. 确认升级
​

**Comment by SeaHOH** [comment]
今天不是很空闲，没人顶上的话我明天来做。

**Comment by SeaHOH** [comment]
@xxnet 确定一下修改目标：
现有自动更新（后台强制）和手动更新（WebUI）两种方式。
- 只修改自动更新；
- 停用自动更新，修改手动更新为自动提示（需打开 WebUI）；
- 两个都改。

**Comment by SeaHOH** [comment]
又看了一下顶楼，是要在升级方式里面加一个“提示”选项吗？

**Comment by xxnet** [comment]
说说​我的想法：
原来的升级设置选项：
1. 不更新
2. 自动升级到稳定版
3. 自动升级到测试版

修改为：
1. 有稳定的新版时，通知（默认设置）
2. 自动升级到稳定版
3. 有测试的新版时，通知
4. 自动升级到测试版
5. 不更新

通知后，有3个选择：
1. 同意，立即更新
2. 不再提示这个版本（需要记录下来本次提示的版本，下次检查到不提醒）
3. 下次再提醒（什么也不做，下次启动会再提醒）

**Comment by onplus** [comment]
http://gra.u2sk.com/?url=https://github.com/XX-net/XX-Net
http://gra.u2sk.com/?url=https://github.com/shadowsocks/shadowsocks-windows

Source code统计不到

**Comment by SeaHOH** [comment]
嗯嗯，有详尽的需求最好。

**Comment by xxnet** [comment]
辛苦了 @SeaHOH

**Comment by SeaHOH** [comment]
我就不拉到本地了，会产生多个 commits。

**Comment by SeaHOH** [comment]
@xxnet 还是交给你来 commit 好点，顺便再测试一下。  [XX-Net-update-tip.zip](https://github.com/XX-net/XX-Net-dev/files/1323054/XX-Net-update-tip.zip)

我只是用假数据简单测试了一下，基本达成目标特性，说下存在的几个问题：
1. 由于 tip 功能限制，显示了三条提示条，视觉效果如下，修改放到一条里面可能更好，或者干脆写一个专门的更新提示条。
![1506035839471](https://user-images.githubusercontent.com/8470820/30723038-1df1987c-9f67-11e7-8a8a-f6f52e678853.png)
1. 我不会调色，你们谁来调好看点，也可以继续改进 css。
1. 自动提醒使用了定时器来获取每日检测保存的数据，其获取频率不会影响每日检测，暂定 1 分钟获取一次，也许有更合适的间隔。
1. 顺便扫一眼有没有可能造成其它问题的修改，毕竟这些代码我不是很熟悉。

**Comment by xxnet** [comment]
1、还是要定制一个提示，放在一行里面显示，里面放3个可以点的链接。
2、调色留给别人就好了，一般不要用红色，除非紧急情况。
3、你是指js的定时器，先1分钟没有问题，需要改再说。
   而每次加载页面时，应该要立即检查一次。

**Comment by xxnet** [comment]
​update.py 250  == 是不是应该为 !=?

感觉提交pull 的话，会比较方便review和交流。

dont_check 和 stop_check 是不是有点混乱？

从stop_check 切换到其他模式，会不会要刷新才能看到结果？

这些测试时一个应该能解决，只是看到就说下。

**Comment by SeaHOH** [comment]
- 的确该 `!=`。
- 主要是你这个仓库太大，不想拉到本地，网页上传 commits 数又太多……
- 这个也不知道怎么好。
- 不是，launcher 这次运行不会再检测了，必须完全退出重启，因为每日检测结束了。

**Comment by xxnet** [comment]
》​dont_check 和 stop_check 是不是有点混乱？
这个，建议采用“可重入” 的思路，即修改状态，一切以状态更新来判断，而不是动作的思路来，会让思路简单。
  具体就是去掉stop_check这个动作，而全部采用dont_check 为判断。
  这算互联网编程的一种思想，多收到几次请求，并没有问题，以最后收到的请求为标准。类似与 set( ) 的语义。

看了仓库，拉回来占磁盘近 100M了。命令行操作是可以这样的，网页也许有问题吧。
https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/
随你，不麻烦就好。

**Comment by SeaHOH** [comment]
要搞成状态判断，那之前退出的每日检测就不对，必须恢复过来，让它一直运行。

其实也没多少手脚了，你自己改改就好，把 dont_check 和 stop_check 都放入 update_info，切换状态时记得保存就行。

**Comment by xxnet** [comment]
好的，剩下的我来搞，辛苦了。

**Comment by wooowooo** [comment]
我写了个能搞多个按键的tip
https://github.com/XX-net/XX-Net/pull/6630

不会jquery, 代码很繁杂

**Comment by wooowooo** [comment]
我觉得以后web可以改成这种版式

就可以随便换页面,而不影响tip

**Comment by onplus** [comment]
重要tip做成托盘气泡？

**Comment by SeaHOH** [comment]
@wooowooo 用框架就不会重载，话说你又把 tip 放到子页面里了，这个才是主页面：
`XX-Net/code/default/launcher/web_ui/index.html`

**Comment by wooowooo** [comment]
目前点一下菜单就相当于刷新了一下整个页面，这要改掉，才能避免换页影响tip。还有似乎现在主页面的架构有点乱，试了一下放tip进主页面，换页时tip会跑到不同的地方。

另外，如果主页面弄好了，tip不受换页的影响了，那么用户手动刷新还是会。这就需要python那边去记录。这需不需要把tip的关闭按钮做成可自定义事件的？

**Comment by SeaHOH** [comment]
感觉 X 大还想改动，不然早就把修改放出来了。

估计就是做成框架式，切换菜单就不会刷新主页面了。
很大可能做一个专门全定义的升级提示条，而不是使用通用的 tip。

**Comment by xxnet** [comment]
1、不同页面切换时，tip条的位置会变化，这个比较奇怪，位置变化不大的话是可以接受的。

2、 tip 的关闭，可以当作“下次再提醒我” 处理


目前有2个想法要做：
1、 x-tunnel 客户端增加http 代理协议的支持，这样手机就可以直接使用x-tunnel作为代理了。
2、x-tunnel 采用websocket 通讯，可以大大降低延迟。


我个人精力有限，所以主要精力只能放在核心算法，希望各位理解。

这个改进， 大家要是有空就先优化下，谢谢各位！

**Comment by wooowooo** [comment]
tip条的位置会变化还是小事，更让人在意的是点一下菜单就相当于刷新了一下整个页面。

tip关闭按钮的点击事件已可用。

**Comment by wooowooo** [comment]
结合了SeaHOH的代码在新分支中https://github.com/wooowooo/XX-Net/tree/tipupgrade ，已将版本调成2.0.0用于测试

@SeaHOH 无法设置升级方式，好像有bug
![default](https://user-images.githubusercontent.com/12052610/30779946-c82ee8be-a131-11e7-873a-a7dacced69ee.png)

    9月 24 14:05:42.53 - [DEBUG] launcher web_control 127.0.0.1:51368 GET /config?cmd=set_config&check_update=stable 
    9月 24 14:05:42.53 - [ERROR] handler:TypeError('set() takes exactly 2 arguments (1 given)',) cmd:GET path:/config?cmd=set_config&check_update=stable from:127.0.0.1:51368
    9月 24 14:05:42.53 - [ERROR] Except stack:Traceback (most recent call last):
    File "/tmp/XX-Net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 138, in handle_one_request
        self.do_GET()
    File "/tmp/XX-Net/code/default/launcher/web_control.py", line 155, in do_GET
        self.req_config_handler()
    File "/tmp/XX-Net/code/default/launcher/web_control.py", line 255, in req_config_handler
        if config.set(["update", "check_update"]) != check_update:
    TypeError: set() takes exactly 2 arguments (1 given)

**Comment by SeaHOH** [comment]
`get` 写成 `set` 了……

**Comment by wooowooo** [comment]
还有，似乎测试版无法通知

**Comment by SeaHOH** [comment]
>​update.py 250 == 是不是应该为 !=?

也是 bug，写错了……

**Comment by SeaHOH** [comment]
修改完毕，麻烦大家测试一下，如果没问题我再 pr。

@wooowooo 没有使用你写的提示条，代码移动到主页面保存。定制了一个，麻烦美化一下 css。

**Comment by xxnet** [comment]
​先赞一个，大家帮忙review、 测试

**Comment by SeaHOH** [comment]
@wooowooo 刚看见你的修改，已合并。

合并之前，还做了点小修改。

大家测试过没有？没啥大问题我就 pr 了。

**Comment by wooowooo** [comment]
还没测试，我这里都快连不上github了。

大家谁有条件的帮测试一下

**Comment by SeaHOH** [comment]
github 直连没问题。

另外， @xxnet 关闭按钮是否必要，似乎去除也可以？

**Comment by xxnet** [comment]
如果保留，好处是，当不知道怎么选时，就点关闭。
去掉的好处，可以让选择更少，容易选择。

你决定吧

**Comment by xxnet** [comment]
完美收工，感谢 @SeaHOH @wooowooo @dou4cc @onplus

**Comment by onplus** [comment]
最新版不能部署服务端，好像被某个新增的js干扰了

**Comment by SeaHOH** [comment]
好像是重定义了 `window.timer` 造成的，改个名称就好。

**Comment by SeaHOH** [comment]
@onplus 麻烦测试一下，我没有用 XX-Net。
https://github.com/SeaHOH/XX-Net/commit/7768a0d7e60b3bee80bc7f2eef7f9aaf5fd26bfe

**Comment by onplus** [comment]
@SeaHOH 修复了请求的问题，没修复部署问题。
[通过对比](https://github.com/XX-net/XX-Net/compare/3.6.13...3.6.14?diff=unified&name=3.6.14#diff-08b2e00cfa55a8ae725b147d55ee7905R77)，我判断是这两个btn冲突了
https://github.com/XX-net/XX-Net/blob/master/code/default/launcher/web_ui/index.html#L79
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/web_ui/deploy.html#L32

注释掉这个新btn，就能点击“开始部署” 按钮了。完整的修复还得请前端高手做

**Comment by SeaHOH** [comment]
部署页面直接用样式获取的按钮，我把按钮改成其它应该就行了。
https://github.com/SeaHOH/XX-Net/commit/73baf7faa2f937d06b94b70bf8d976f98d53a681

**Comment by SeaHOH** [comment]
哪一个更新提示，就是新加的这个吗？

**Comment by onplus** [comment]
是我改错了。。。应该可以提交了@SeaHOH

**Comment by SeaHOH** [comment]
了解~
