### ISSUE TITLE
有关GreatFire的讨论

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#44]
[之前的讨论](https://archive.is/FVUBi)
@guo392 在人家的地盘和人家硬肛不好玩~

**Comment by dou4cc** [comment]
我现在的一个疑问是greatfire“团队”到底是从外而内瓦解还是从内而外瓦解，和政府交接持续一个月，这叫什么事嘛！

**Comment by xxnet** [comment]
要收集最原始的资料，自己进行分析。

**Comment by dou4cc** [comment]
刑侦和接受捐助好像不矛盾啊，freebrowser加了后门之后把捐款入口也去掉了，不懂怎么想的~

**Comment by dou4cc** [comment]
greatfire简直了，不但不再接受捐助，freebrowser还出了阿拉伯版：https://twitter.com/GreatFireChina/status/911924972758724608

**Comment by candy2107** [comment]
@dou4cc 
蓝灯的中文管理员被销号,你知道什么情况么
https://github.com/getlantern/forum/issues/833

**Comment by candy2107** [comment]
@dou4cc 
封锁升级，YouTube、Facebook已经被加入特殊照顾名单，待遇与*.twitter.com相同。若使用官方IP（ipv4）经过防火墙时一旦探测到相关域名的CA证书，对应IP通信百分之百被拦截切断。

**Comment by dou4cc** [comment]
@candy2107 官方ip是什么鬼啊？推特的话，就算我走境外sni也是会reset的耶！

**Comment by candy2107** [comment]
@dou4cc 
原文在这里 https://github.com/sy618/hosts/blob/master/README.md
意思是 证书封锁升级 , 官方ip失效 , sni ip可能失效

**Comment by xxnet** [comment]
​证书封锁，应该是针对hosts 方案。

梯子策略：
   跳过被污染的DNS，自己写hosts
   如果能连上，效果确实非常不错。
   免费、成本极低。

GFW策略：
   TLS握手阶段就过滤掉。
