### ISSUE TITLE
清理php模块以及更新pac-server.py

### ISSUE THREAD

**Issue by ghost** [XX-net/XX-Net-dev#45]
我看这个目录下的也没用了 python27/1.0/lib/noarch/dnslib
更新pac-server.py为xx-mini的最好  https://github.com/xyuanmu/XX-Mini/blob/master/lib/pac_server.py

**Comment by xxnet** [comment]
python27/1.0/lib/noarch/dnslib 
先留着，以后有用，可以做一个DNS over HTTP，解决DNS 污染的问题。

PAC 还需要大家多做测试。
