### ISSUE TITLE
[小建议]修改代理状态检测

### ISSUE THREAD

**Issue by onplus** [XX-net/XX-Net-dev#46]
所有的检测都不一定准确，能翻墙才是硬道理。
直接在状态页嵌入一段gist或者wiki，

**Comment by xxnet** [comment]
​恩，这个主意不错

**Comment by onplus** [comment]
用着x-tunnel，却纠结着gae的状态
https://github.com/XX-net/XX-Net/issues/6836

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/commit/b095214311e54f43cdc47131376f1a8a9db8567f

**Comment by xxnet** [comment]
似乎没有人报证书问题了
