### ISSUE TITLE
这是什么警告

### ISSUE THREAD

**Issue by CongZeng** [XX-net/XX-Net-dev#5]
May 03 14:51:00.275 - [WARNING] gae_handler.handler send response fail. e:error(10053, '') https://r11---sn-vgqs7n7s.googlevideo.com/videoplayback?id=hgIfZz8STLk.2&itag=135&source=yt_live_broadcast&requiressl=yes&gcr=us&playlist_type=LIVE&ratebypass=yes&cmbypass=yes&mime=video%2Fmp4&live=1&gir=yes&signature=30C12DBFD1F0A0C2EE0708A07095F661BDEFF8D9.17CFC8D3FA9FD68B0E736AC627764ED4249C5F92&fexp=9413137,9416126,9416891,9417367,9419550,9422596,9424653,9428398,9428742,9429103,9431012,9431623,9432058,9433096,9433184,9433275,9433460,9433622,9433946,9434290,9434746,9434801&key=cms1&upn=iPejuzr_TEw&sver=3&cpn=gRts_fF01gzW8y0R&mpd_version=4&pacing=0&ip=107.178.194.114&ipbits=0&expire=1462279837&sparams=cmbypass,expire,gcr,gir,id,ip,ipbits,ipbypass,itag,live,mime,mm,mn,ms,mv,pl,playlist_type,ratebypass,requiressl,source&pl=27&alr=yes&keepalive=yes&c=WEB&cver=1.20160428&redirect_counter=1&req_id=49af6424698ea3ee&cms_redirect=yes&ipbypass=yes&mm=32&mn=sn-vgqs7n7s&ms=lv&mt=1462258207&mv=m&sq=1523520&clen=454986&lmt=1462258237291898&dur=5.0&rn=6&rbuf=4800

**Comment by xxnet** [comment]
​给浏览器发送数据时，浏览器主动断开，比如浏览器窗口已经关闭。

查找特定日志的意思，可以通过关键字，在源码中搜索。

**Comment by pgz123** [comment]
3.12在哪里下载？

**Comment by jzp820927** [comment]
@pgz123 https://github.com/XX-net/XX-Net/releases

**Comment by pgz123** [comment]
@jzp820927 谢谢
