### ISSUE TITLE
隔壁说这次ip封锁是针对XX-Net而来的

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#50]
若真如此，@xxnet可以往ip库里放一些微软、苹果、学术期刊的ip，让gfw那帮人好好把ip检查一遍，然后你再把ip库更新频率提高一点，趁gfw那帮人没搞定就发新版。

**Comment by SeaHOH** [comment]
这么做没有意义，最多上当一次……

**Comment by SeaHOH** [comment]
P2P 啊，暴力开路~
求进度

**Comment by dou4cc** [comment]
😔

**Comment by kirbyzhu** [comment]
隔壁社长哪去了？
