### ISSUE TITLE
[请求协助] 注册顶级域名和cloudflare帐号

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#51]
想验证一个想法，需要一些顶级域名和单独的cloudflare帐号。

域名要用国外的注册商，不要用国内的。
顶级域名用最便宜的 .online, .xyz 之类的就好，成本是1年 不到2美元，很多默认买2年。
cloudflare注册帐号，然后绑定注册的域名，这一步如果不会，也可以交给我。
这样一套成本2美元，我可以把这个费用给回你。

注册之后，把域名管理帐号、cloudflare帐号、管理密码都发我邮箱。
建议用一个随机的密码。

发到：xxnet.dev@gmail.com

感谢！

**Comment by wooowooo** [comment]
我记得有免费的.tk
