### ISSUE TITLE
[方案讨论] 启用ipv6的自动化

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#53]
参考： 
https://github.com/XX-net/XX-Net/issues/6918

这个过程能否完全自动化？

**Comment by onplus** [comment]
win7 / win10专业版 用组策略 ，看图操作
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1580771

Windows 环境太复杂了，全自动化不容易
https://support.microsoft.com/zh-cn/help/929852/how-to-disable-ipv6-or-its-components-in-windows

linux 可以装miredo。

小白可以用6plat（不考虑安全因素）

**Comment by xxnet** [comment]
​就是复杂，自动化才更加有意义。
当然难度不少。
也许初期可以考虑做成辅助判断出问题在哪里，再逐步完善。
需要有脚本高手来处理啦

**Comment by EmmieMcDonald** [comment]
我感觉做「一键」翻墙有两个悖论

一是 GFW 故意留下的缺口与大用户量的矛盾
翻墙是 GFW 故意留下的缺口，TG 可以容忍少部分获取信息能力较强的人通过梯子出去，但全民翻墙则不被容忍．从每次敏感时期工具的大面积瘫痪，英文网站与文化程度较高的民众使用的网站封禁程度较轻，如quora github 存，facebook youtube 亡，可以看出这一点
如果做成一键翻墙，肯定越过 GFW 的底线，势必要在技术上完全压制 GFW，而不能从 GFW 放松的缺口中出去

另一个是，需要「一键」翻墙的人，通常不需要翻墙
通过对身边人群的观察，发现很多人经常提问「翻墙做什么」，或者翻出去了不到五分钟自己滚回来．语言障碍与多年墙内生态的适应，让大部分人停留在使用墙内替代品的舒适区，没有动力出墙去接受新事物

初次配置有难度，长期使用很方便，应该是一个不错的发展方向

**Comment by dou4cc** [comment]
@EmmieMcDonald gfw不再会有缺口了

**Comment by xxnet** [comment]
​不是故意留下的缺口，而是有些通道他不能关闭，要关就断网了。

**Comment by EmmieMcDonald** [comment]
@dou4cc 
尘埃飞扬，待尘埃落定吧，等月底看看

@xxnet 
嗯，翻墙缺口可能是不充分的完全堵死意愿、技术能力、误封代价与成本代价的综合作用

**Comment by SeaHOH** [comment]
一键断网，其它国家已经搞过几次了。

**Comment by SeaHOH** [comment]
开发更多、更健壮的通道是有必要的。

**Comment by dou4cc** [comment]
你们啊，一键来一键去的搞得我扑哧笑出来

**Comment by SeaHOH** [comment]
不要笑，这是真事，直接全国离线。

**Comment by dou4cc** [comment]
（苦笑

**Comment by xxnet** [comment]
​全国断网，这是我们的胜利！

**Comment by SeaHOH** [comment]
评当前手段，还不能使党国这么做，加油！

**Comment by onplus** [comment]
win7 旗舰版 SP1 X64 测试成功

https://github.com/XX-net/XX-Net/issues/7051#issuecomment-335477041

**Comment by xxnet** [comment]
已经把这个文件：
https://github.com/XX-net/XX-Net/files/1381759/IPV6.zip

放到:
https://github.com/XX-net/XX-Net/tree/master/code/default/ipv6_script

**Comment by xxnet** [comment]
脚本已经就绪，就差UI交互了。
可以这样：

GAE的状态页面里，检测本地IPv6是否开通，如果无法扫描到ip，可以建议用户去开启IPv6。
  跳转到：

GAE的高级页面里，有一个叫IPv6的页面
  里面有当前IPv6开启状态，如果未开启，有开启按钮，下面是执行的命令行情况日志。
  如果已经开启，按钮显示关闭。

不同操作系统，执行不同的命令，不支持的操作系统，现实暂不支持。
  必要时，会弹出管理员认证。
  这些接口在导入证书已经实现的了，可以参考。

**Comment by LakeishaKowalczyk** [comment]
关闭 IPv6 时，如果可以执行一个脚本，撤消所有操作（比如 dns 优先级）就更好了

**Comment by xxnet** [comment]
​应该可以的

**Comment by xxnet** [comment]
开任务了 
#65

**Comment by gjbg1989** [comment]
3次运行的结果：
Win10专业版运行3.7.17下的 (disable_ipv6.bat) enable_ipv6.bat ，启动IPV6正常但输出日志文件出错：丢失了日期_以后的参数及扩展名，如 ipv6-state2017-11-16_ （大小非0）
同时记事本报错：找不到正确的日志文件，确认建立文件，生成完整文件名的0大小空文件。

**Comment by xxnet** [comment]
​@onplus

**Comment by gjbg1989** [comment]
3.7.17启动IPV6输出日志文件：现在已正常一次，是修复了还是原来有使用 Pcap_DNSProxy 的缘故？

**Comment by onplus** [comment]
@gjbg1989 执行路径是code/default/gae_proxy/local/ipv6_tunnel 吗

应该是这一部分引起的
```
set time=%date:~0,4%-%date:~5,2%-%date:~8,2%_%time:~0,2%%time:~3,2%%time:~6,2%
@call :output>..\..\..\..\..\data\gae_proxy\ipv6-state%time%.txt 
exit
```

**Comment by gjbg1989** [comment]
执行路径一直是code/default/gae_proxy/local/ipv6_tunnel，出错与否只是有无使用 Pcap_DNSProxy 的区别

**Comment by whhxmwhh** [comment]
我的天呀。原来各位老大在这里忙着呢。。可是我IPV6是在是很蛋疼！～
