### ISSUE TITLE
[紧急] 请X大停止开发XX-Net，转向去中心化网络。

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#54]
https://twitter.com/wangDevming/status/917729699824111616

@xxnet

**Comment by dou4cc** [comment]
@xxnet 讲真你的应急能力不如phuslu。把XX-Net弃掉，让那些只用XX-Net的人歇半个月吧~

**Comment by EmmieMcDonald** [comment]
蓝灯不是也

**Comment by xxnet** [comment]
​还有办法，只要把足够多的云服务器通道搭好，就可以了。
亚马逊也有云。

**Comment by dou4cc** [comment]
@xxnet 都白名单了，aws能用几天？

**Comment by xxnet** [comment]
ipv6 和 X-tunnel 都还有潜力，继续

**Comment by SeaHOH** [comment]
可以继续，没问题。

但是下一个项目也应该开始准备，不然到时可能接不上。
折腾能力够的人是不在意，大部分人可能就没辙了。

**Comment by xxnet** [comment]
​I2C 一直都可以，就是速度太慢，可以最为最后的通道。
x-tunnel的通道可以有很多种。

另外tor也是可以折腾的，虽然不快，但是各种云前端都现成的。

**Comment by dou4cc** [comment]
@xxnet 如果真的断外网了，tor是指望不上的。i2p并不可取，你看现在迅雷已经被整了，下一个就是BT、DHT。

**Comment by xxnet** [comment]
​你是觉得很快会断外网了吗？

**Comment by dou4cc** [comment]
@xxnet 你看顶楼链接，山东莱芜已经试点了。跳板并不可靠。

**Comment by xxnet** [comment]
​网络应该是通的，只是域名白名单而已，除非特别混乱，不过还没有到那一天吧

**Comment by dou4cc** [comment]
@xxnet 只是dns白名单不可能如@wangdevming所言所有不走跳板的梯子失效。

**Comment by SeaHOH** [comment]
普通跳板都开始失效了，下面这种方案还可以用，很容易实现。
跟 X-tunnel 思路差不多，个人使用效果很好。
http://www.ttlsa.com/linux/bind-stunnel-sni_proxy-secure-proxy/

@xxnet 能问一下 P2P 的开发进度吗？

**Comment by xxnet** [comment]
​P2P 还没有开始，先把代理做好吧。

P2P 和代理是互相补充的，P2P如果没有种子，也是无法启动的，而获得种子，必须先连上中心服务器。
类似BT的Tracker。

**Comment by xxnet** [comment]
​这个方案和SS/v2ray 有什么本质差别？

**Comment by SeaHOH** [comment]
kad 就是去中心的，再加上作为服务运行一直保持在线，既可以壮大网络，也可以很容易在下次启动时接入。

要说本质差别，似乎没有。
上面的方案直接套用 TLS 加密没有明显特征、只需维护一份 hosts 列表。

**Comment by xxnet** [comment]
zeronet 是很不错的基础，而且也是python实现。
先吸收学习，再在上面定义好的产品形态。
