### ISSUE TITLE
关于更新后版本号错误的研究

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net-dev#55]
> 更新完成后，取得的 当前版本 还是旧的

我做了试验。先写最终我的推论：浏览器本来连接上了8085，更新完成后旧进程仍然运行，浏览器继续与旧进程通信，故所得版本号是旧的。新旧进程同用一个终端，终端显示的旧版本号log是旧进程输出的。

细节：

更新完成后，“重启”创造了新进程，旧进程始终不退出，直到你关闭xx-net。
重启后8085被新进程监听了，但浏览器原本建立起的连接仍然存在。重启浏览器再打开web，才是与新进程通信。

ps:点击web上的退出按钮并没有完全退出xx-net，而是成为僵尸进程。直到在终端中ctrl-c。

测试环境： Linux , Firefox

    watch -n 0.2 "netstat -lapn|grep 8085"

**Comment by xxnet** [comment]
​先排除是不是某个模块退出太慢了，比如发出的请求还未返回。
python 如果有线程未退出，主线程结束也不会退出。

**Comment by onplus** [comment]
win7 chrome 复现，两个模块已经先手动关闭了
![adf](https://user-images.githubusercontent.com/31188782/31493466-e6f65490-af81-11e7-960b-56e7d6065f80.JPG)

**Comment by wooowooo** [comment]
我也已关了两个模块

**Comment by xxnet** [comment]
试试访问：
http://127.0.0.1:8085/quit
看能否关闭进程


试试开一个进程
然后另外再开一个进程，第一个会不会退出

**Comment by SeaHOH** [comment]
我试过完全退出 `os._exit`，然后 web 界面就卡死了，必须强制刷新才能连上新进程。

**Comment by SeaHOH** [comment]
持久连接的锅？

**Comment by wooowooo** [comment]
我也试过升级下载时关掉浏览器，但旧进程还不关

**Comment by xxnet** [comment]
似乎找到问题了，

函数 restart_xxnet里
os._exit(0) 被注视掉了

代码已提交.

**Comment by SeaHOH** [comment]
>我试过完全退出 os._exit，然后 web 界面就卡死了，必须强制刷新才能连上新进程。

我说的就是这个地方。
launcher 的旧连接（127.0.0.1:8085）没有断开，需强制刷新。
不知道其它模块如何，没试过。

**Comment by xxnet** [comment]
​发现新进程会带者旧进程的监听端口，所以要在启动新进程之前，关闭所有监听端口。
这就不能让新进程来关闭旧进程了。

web界面卡死，应该是浏览器的问题，只能在js上想办法了。
