### ISSUE TITLE
[TODO]智能路由开发

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#57]
先按之前的讨论，规则先用python写，以后再做成可配置的。
可配置，可以逐步发展。

v2ray的配置规则，用json写，比较复杂。
也不是不可以，规则留给少部分人来改，大部分情况是不用改，
少数情况下，Web界面上设置就好，比如某个域名/url要走特定的通道。

**Comment by SeaHOH** [comment]
先在 XX-Net 定义一个比较通用接口，路由模块单独放一个仓库，以后可以用到其它地方。

**Comment by xxnet** [comment]
​其实项目里有很多模块是通用的，很多地方可以用到。
不过为了方面用户下载使用，都是放在一个项目里。

当然要是把模块化下载实现好，就可以把项目拆出来，客户端需要哪个模块，就去下载，也可以让下载包变小很多，更新更细粒度。

**Comment by pluslu** [comment]
https://raw.githubusercontent.com/h2y/Shadowrocket-ADBlock-Rules/master/sr_top500_whitelist_ad.conf
做出来之后能否套用shadowrocket的这套规则

**Comment by xxnet** [comment]
很不错的规则
先收藏，解析一下这个格式很容易。
可以考虑客户端定期更新这个连接。

**Comment by dou4cc** [comment]
@pluslu 请改名。

**Comment by xxnet** [comment]
目前基本开发完成，接下来根据反馈进行调整和修bug
