### ISSUE TITLE
linux下如何使用http/2

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#6]
尽量用最新的linux发行版本，可能系统提供的python-OpenSSL包能够支持。
可以看状态页里OpenSSL的版本信息，看是否支持。

如果不支持，需要卸载系统的python-OpenSSL
然后启动xx-net，看缺哪些包，按照这些包。

希望能够找到比较通用的办法来解决这个问题。

**Comment by jzp820927** [comment]
能不能在不卸载系统包的情况下，直接使用 xx 的包？

**Comment by xxnet** [comment]
​可以，修改 code/default/launcher/start.py
 把 sys.path.append(linux_lib)
 改为 sys.path.insert(0, linux_lib)

**Comment by jzp820927** [comment]
额，其实我想表达的意思是，能不能做成自动判断，如果系统包支持 http2，就用系统的包，如果不支持，就调用 XX的包？

**Comment by xxnet** [comment]
​我也有这个设想，需要把异常情况处理好，然后选择最优结果

**Comment by jzp820927** [comment]
好吧，希望能有实现的一天。good luck

**Comment by zjhzxhz** [comment]
我觉得会用Linux的人一般都是程序猿，都会折腾。
所以给个提示告诉程序猿该怎么做就好了吧。该编译编译，该干嘛干嘛。
