### ISSUE TITLE
xiaolan删掉了ta的github账号

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#60]
@xxnet 你报个平安！

**Comment by qwerttbb** [comment]
谁是小蓝

**Comment by dou4cc** [comment]
@qwerttbb 
https://archive.is/4fuWS#selection-519.227-519.234
https://archive.is/xiaolan.me

**Comment by dou4cc** [comment]
@yeahwu https://twitter.com/dou4cc/status/920623191441145856

**Comment by onplus** [comment]
你发了才一个小时就敢报失踪？

他 今天早上还回复了我

**Comment by dou4cc** [comment]
@onplus 一个半小时了。
你得知道，xiaolan删github是件大事，肯定伴随其它事情。

**Comment by dou4cc** [comment]
@xxnet出现奇怪言论：https://archive.is/iP30S#selection-1099.1-1099.24

**Comment by xxnet** [comment]
​大家都换匿名帐号来讨论吧，建好匿名系统再来，不要整天担心

**Comment by dou4cc** [comment]
@xxnet 匿名的关键是不放弃原有身份。

**Comment by xxnet** [comment]
​身份丢掉吧，没什么所谓的。
必要时可以私下给我发个邮件

**Comment by dou4cc** [comment]
破娃被人肉就是因为时间窗口分析
