### ISSUE TITLE
不自动导入证书

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net-dev#61]
把选择权留给用户。我始终觉得翻墙软件不应该主动在用户的电脑上留下痕迹。

我大致看了一下cert_util.py，好像只要注释掉这个
https://github.com/XX-net/XX-Net/blob/50dbf5cc023664801a73cf21714f92bad2ad725a/code/default/gae_proxy/local/cert_util.py#L584
再在web中加个按钮“导入证书到系统”调用。（UI我可以弄弄）

至于导入浏览器，点下载按钮就很好了。
https://github.com/XX-net/XX-Net/blob/50dbf5cc023664801a73cf21714f92bad2ad725a/code/default/gae_proxy/local/cert_util.py#L548
这个函数我觉得就没有必要用了。

**Comment by xxnet** [comment]
非常​同意你的观点。

UI的引导做好了，就OK了。

**Comment by xxnet** [comment]
​不过貌似目前的自动导入的方案，并没有什么副作用？

**Comment by wooowooo** [comment]
geek们心里不舒服，哈哈。

那个ui弄在哪里好？

**Comment by xxnet** [comment]
​不自动导入，应该会多一些人反馈问题，不过可以先试试再说。

想到的流程：状态页检测到证书没有导入，旁边显示一个按钮，一键导入，旁边一个wiki的说明链接。
  按钮点击之后，提示用户刷新？

不过目前的证书导入判断不稳定，经常要Ctrl+F5才好，能否解决？

**Comment by onplus** [comment]
post好像是忽略缓存的

[code/default/gae_proxy/web_ui/status.html#L495-L500](https://github.com/XX-net/XX-Net/blob/50dbf5cc023664801a73cf21714f92bad2ad725a/code/default/gae_proxy/web_ui/status.html#L495-L500)
```
        $.ajax({
            type: 'GET',
            dataType: 'text',
            crossDomain: true,
            timeout: 1000,
            url: 'https://www.twitter.com/xxnet',
```

**Comment by wooowooo** [comment]
状态页的引导是要做好。
我想增加个gae菜单 证书工具（或者能够在个现有的页面里插入？）

> 
> 证书信息
>   生效日期：
>   有效期至：
> 
> 链接-wiki
> 下载证书到当前浏览器：按钮-下载
> 自动导入证书到系统： 按钮-导入   按钮-移除
> 
> 按钮-重新生成证书

这是UI。有些功能还没有，先隐藏对应UI起来

**Comment by xxnet** [comment]
​这个可以放在高级页面里，很多非技术用户不知道证书是什么呢。

然后是否导入证书，做成配置，默认是自动导入，给普通人用，特别是新用户，第一次使用的门槛越低越好。
高级用户可以在高级页面里，关闭自动导入证书，显示当前证书的信息信息等

**Comment by wooowooo** [comment]
刚刚我还pr想改掉高级的名称，因为都被ip相关的占满了(°_°)。。。。。

如果在状态页给出足够多的引导和提示，是否能够不用默认导入呢？(高级用户也不明不白的被导入了)

**Comment by xxnet** [comment]
​从体验上讲，新用户的门槛是越低越好，最好就是打开后就一切OK。
要定制再慢慢摸索。

所以，可以在证书管理页面里，放上删除已导入证书的功能，这样就干净了，当然这个功能还没有开发。

优先保证用户启动XX-Net后能用起来，其他的再说。
高级用户嘛，可以手动修改配置文件，再启动的。。。

**Comment by wooowooo** [comment]
听你的。
我觉得目前的 高级 里全是与ip有关的，不如就改名算了。
证书ui放配置里，可收缩，怎样？

**Comment by xxnet** [comment]
​可以。
收缩起来，就清净了。

**Comment by wooowooo** [comment]
https://github.com/XX-net/XX-Net/compare/master...wooowooo:optional_cert?expand=1

用户可以设置环境变量`XXNET_NO_MESS_SYSTEM`或配置`no_mess_system`来阻止软件导入证书和创建快捷方式,这样是否可以?

另外
https://github.com/XX-net/XX-Net/blob/c666bde17045d421c2e8c7a192d519b0b918bcc4/code/default/launcher/config.py#L64-L94
这个函数是不是忘了改变`need_save_config`

**Comment by xxnet** [comment]
2017-10-29 18:11 GMT+08:00 wooowooo <notifications@github.com>:

> https://github.com/XX-net/XX-Net/compare/master...wooowooo:
> optional_cert?expand=1
>
> 用户可以设置环境变量XXNET_NO_MESS_SYSTEM或配置no_mess_system来阻止软件导入证书和创建快捷方式,这样是否可以?
>
这个设计不错。

另外:
原来 cert_util.py 565行，删除，你测试过没有问题吗？
我记得有的平台如果不删除，会累积出来很多个证书。
具体需要测试验证。


> 另外
> https://github.com/XX-net/XX-Net/blob/c666bde17045d421c2e8c7a192d519
> b0b918bcc4/code/default/launcher/config.py#L64-L94
> 这个函数是不是忘了改变need_save_config
>
看代码好久，我也看不明白，因为确实逻辑上有问题。
可是实际上没有报bug。
最后找到丢失 need_save_config的一次更改：
7fd7a177c003ffe0a0ead9ce33bdb9b6bbeba1ac

分析结论如下：
a. 确实是忘记设置 need_save_config
b. 实际中并没有导致什么异常，是因为：
  在别的地方，还是会触发保存配置。
  就算不保存配置，本次check检查的作用，下次启动还会再作用一遍，这和保存配置的最终结果一样。
c. 要不要修正？要。
   可以改进成：
  need_save_config 为全局变量，每次set时，设置为True
  save 之后，设置为False

**Comment by wooowooo** [comment]
`CertUtil.remove_windows_ca`没有删除.是移动到新553行了,这样可否?我还没测试,等有windows用先.
https://github.com/XX-net/XX-Net/compare/master...wooowooo:optional_cert?expand=1#diff-ba9359e51b79a7d26992f6df75076f3eR553

config的我修复了在新的commit里,看看对不对

**Comment by xxnet** [comment]
已完成
