### ISSUE TITLE
白名单来了

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#62]
https://archive.is/tqXwd

**Comment by onplus** [comment]
建议去UC发

**Comment by xxnet** [comment]
​这是墙无奈了吗

**Comment by dou4cc** [comment]
@xxnet 我这儿也挂了，南京电信。

**Comment by xxnet** [comment]
​所有外网ip都无法联通吗？github可用？

3.7.4 的x-tunnel 状态页贴来看看

**Comment by dou4cc** [comment]
@xxnet 所有已知国外网站都不能直接访问。github不可用。
我不用x-tunnel。要不你写个测网络环境的脚本让我跑？

**Comment by xxnet** [comment]
​x-tunnel 目前连接GAE/cloudflare/heroku，其状态页就可以反映一些问题

测试网络环境，要先想好测试哪些东西。
DNS往往是最先最容易封的，而ip封了就物理断网了。

**Comment by dou4cc** [comment]
@xxnet 南京移动访问墙外网站连通性正常，fast.com速度不到25Kbps。对我的梯子来讲，这种速度算作不通。

**Comment by dou4cc** [comment]
@xxnet 见鬼，南京移动连国内速度（不管连哪个isp）都不到1Mbps了。测试时没开梯子，没有异常nslookup。

**Comment by xxnet** [comment]
国外的ip能ping通吗？

**Comment by dou4cc** [comment]
@xxnet ping有卵用？你晓得不是伪造的？还在打PTunnel的算盘？

**Comment by onplus** [comment]
@dou4cc 你不维护项目，不提pr，不写wiki，不答issues？光造谣有卵用？

**Comment by SeaHOH** [comment]
传说中的鲶鱼？好像哪里不对~

**Comment by xxnet** [comment]
​@dou4cc
  不要太紧张，目前的形势，还不到断网的时候。
