### ISSUE TITLE
白名单应对策略

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#63]
- 移民
- 卫星上网
- 自组织网络
- 自动化黑入公司网络，以其为跳板翻墙

欢迎补充。

**Comment by SeaHOH** [comment]
☭☭☭

**Comment by xxnet** [comment]
​p2p啦

**Comment by dou4cc** [comment]
你们心理素质真好，我这儿墙内sniproxy死了一片。

**Comment by xxnet** [comment]
sniproxy 很容易封， sni和证书都是明文的，要封只是动动手而已

**Comment by SeaHOH** [comment]
考虑封锁成本，现阶段范围不会太广，以后就不好说了。

**Comment by xxnet** [comment]
至少1年内不必担心断网，除非发送重大变故

**Comment by dou4cc** [comment]
果然不能指望你们

**Comment by xxnet** [comment]
​智能路由，IOS支持，Android 自动配置，很多事情要做啊

先做好一个，再去开始另一个工作，p2p不是简单的项目，一开始估计要半年才能拿得出手。
这些任务都不算太简单，有很多需要摸索

大家一起来搞如何？我一个人精力有限

**Comment by SeaHOH** [comment]
框架先设计好，尽量细分功能模块。

只要不是太复杂，指明要求，我可以接一些 Python 方面的任务。

**Comment by qwertccc** [comment]
p2p？

主要问题是你用户绝大多数都在国内，转半天出不去不也白搭

除非设计理念上登高过墙就是个附带属性，主要任务属性是那种可以吸引老外一起用的，比如高匿

那么如果真的定义为高匿，跟tor有啥区别啊，不如加入tor的工作，增加一些去中心化的类似kad的不可识别的协议一类的玩意儿。。。。

现在tor的obfs4已经完全被识别，meek也贼慢而且抗封锁能力太差，除了高匿以外没啥优势了

**Comment by xxnet** [comment]
@SeaHOH
  好的，我接下来把一部分工作进行细化设计，大家分工。
  团队作战才有战斗力。



​不一定要完全自己开发，重建高楼。
看zeronet 就挺不错的，除了它的产品设计。太技术化，缺乏用户体验引导。
可以在上面进行封装，改成我们需要的样子，必要的底层修改也可以提交到zeronet上。

p2p不一定要做成Tor的模式，如果物理断网了，能够在墙内交流就可以了。
甚至在线下，通过手机对手机进行直接互换信息，只要产品设计得好，也是不错的。

**Comment by dou4cc** [comment]
p2p面临很多挑战。目前还没有什么高匿工具能在断外网的条件下工作，能在断网条件下工作的就更没有了。所以你要动工的话，高匿必须是其中一个功能。然后，ZeroNet是完全不抗封锁的。未来在断了外网的墙内和tg斗，肯定也只能见招拆招，设计不出一劳永逸的抗封锁去中心协议，所以模块化、版本跌代什么都是很头疼的事。

**Comment by xxnet** [comment]
最近开始封非通用端口，基本上目前的p2p应该封掉了。

新的p2p必须重新设计，因为一般的p2p只是考虑去中心，极少考虑封锁。
不过前人的p2p实现，有很多东西可以学习的。

**Comment by SeaHOH** [comment]
可能分地区实验，我这儿 P2P 还可以连外面。

**Comment by xxnet** [comment]
​实现匿名，并不难，可以参考tor和twister。
抗封锁，稍微麻烦一些，不过也不是完全不可能。

**Comment by dou4cc** [comment]
适配古巴硬盘互联网的通讯协议：https://zh.wikipedia.org/zh-cn/%E4%BF%A1%E9%B8%BDIP%E9%80%9A%E8%AE%AF

**Comment by tec1987** [comment]
@dou4cc
你这是打算引领我们倒退50年吗？
