### ISSUE TITLE
[任务] 检测浏览器证书状态

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#66]
### 问题：
  经常反馈浏览器证书状态Fail，可是能翻墙。  
  需要Ctrl-F5 刷新才行。

### 解决方案：
  改 GET模式为POST，避免浏览器缓存

### 难度：1星

**Comment by SeaHOH** [comment]
先选个简单的，其它的我都没有使用。

**Comment by SeaHOH** [comment]
@xxnet 刚才看了，好像只改两个单词就行，你确定这需要发任务？

**Comment by xxnet** [comment]
​测试好了就提交吧，有时确实工作量不大，有时调试花很多时间

**Comment by SeaHOH** [comment]
我之前没改也是正常显示的，测这个只能靠运气碰？

**Comment by xxnet** [comment]
​要不就先把它弄成不正常，比如删除CA证书，换一个一样的。

要不就先提交，等用户反馈问题了，再去研究啦

**Comment by xxnet** [comment]
已发布，感谢！

https://github.com/XX-net/XX-Net/issues/7875

**Comment by wooowooo** [comment]
还有一种情况。
当浏览器的代理设置不是gaeproxy的时候，证书检测总是fail。

**Comment by xxnet** [comment]
​可以在x-tunnel 里，返回一个特殊结果，并显示相应的信息。

**Comment by wooowooo** [comment]
可不可以用js指定向gae端口发送

**Comment by SeaHOH** [comment]
>可不可以用js指定向gae端口发送

好像不行，做成扩展可以。
