### ISSUE TITLE
[任务] X-Tunnel 服务器选择

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#69]
### 功能：
  登陆指定的服务器

### UI:
  在Config页面中，增加一Tab，Select 特定的服务器。
  默认是自动。

### 底层实现： 
  login center 时，返回可选的服务器列表和名称
  选择特定服务器时，修改config，重新登陆。

### 任务说明：
* 难度: 2星
* 需要技能： html5, python
* 说明：开始前，请留言

**Comment by xxnet** [comment]
login center 时，返回可选的服务器列表和名称:

login/register 返回的信息中，增加了：
“selectable": [ [host, name, location], ]

**Comment by xx-Chen** [comment]
> “selectable": [ [host, name, location], ]

没见阿..😂

**Comment by xxnet** [comment]
服务端有返回这个数据，在json中，只是客户端没有解析出来而已。
用调试工具设个断点，或者手动print出开可以看到

**Comment by xxnet** [comment]
Thank you for your work.
