### ISSUE TITLE
[任务] X-Tunnel 状态页改进

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#70]
### 新增功能：
* 代理绑定的ip，端口
* 已处理请求数（帮助分析问题，很多用户没有修改代理端口）
* 1 分钟流量统计
* 网络延迟  
  可以roundtrip 的延迟，减去服务端阻塞时间。
  统计10秒内最高

### 任务说明
* 难度： 2星
* 需要技能，python为主，需要一点html5/js

**Comment by SeaHOH** [comment]
```py
rtt = roundtrip_time - time_cost
```
`time_cost` 就是服务端阻塞时间吗？已经算出来了？

**Comment by xxnet** [comment]
是的，阻塞时间 = roundtrip_time - time_cost

**Comment by SeaHOH** [comment]
>阻塞时间 = roundtrip_time - time_cost

写错没有？是不是
网络延迟 = roundtrip_time - time_cost

**Comment by xxnet** [comment]
​恩，你的理解是对的。

我的”阻塞“ 是指被GFW阻塞住的意思，确实用词不准确。

**Comment by SeaHOH** [comment]
ok，理解了。
感觉能做，接了。

**Comment by SeaHOH** [comment]
>1 分钟流量统计

这个是否统计发送流量？如果要，非 200 响应的请求是否也在统计范围？

**Comment by xxnet** [comment]
Exciting!

都统计吧，非200响应就不要统计了。

**Comment by SeaHOH** [comment]
https://github.com/SeaHOH/XX-Net/tree/x-tunnel-debug

简单测试了一下，没有试 GAE front。

>已处理请求数

是用成功和失败次数直接相加的。

>1 分钟流量统计

1 分钟没活动就会归零，有没有必要统计总流量？

**Comment by SeaHOH** [comment]
![1509365651213](https://user-images.githubusercontent.com/8470820/32170318-078d614a-bdaf-11e7-9bd8-94189f25db5b.png)

**Comment by SeaHOH** [comment]
题外话：X-Tunnel 注册真是完全没有门槛，不怕被攻击吗？

**Comment by xxnet** [comment]
很好。


提点修改意见：
* 流量统计
  每一个front可以直接统计累计，不需要统计最近的了。
  然后全局，有一个统计 最近的速度的，名字可以四speed， 内容放在一行里： Up:xx/Down:xx，可以考虑5秒或3秒统计一次。

* 已处理请求数
  原来想法是：已处理TCP连接数。
   是proxy_handler 里处理的连接请求数量。

  目的： 如果是0， 很可能用户还没有设置好浏览器的代理端口。

  应该是全局的，不是每一个front的。

* Round-trip time
 只统计全局就好了，我们关注用户体验。
 名字改为response time 如何？


服务端成本很低，攻击没有什么意义。
实在需要，再加邮件验证吧

**Comment by SeaHOH** [comment]
这回如何？
https://github.com/SeaHOH/XX-Net/tree/x-tunnel-debug
![1509376246192](https://user-images.githubusercontent.com/8470820/32178827-b5f5387a-bdc8-11e7-8147-a632c93783f6.png)

**Comment by xxnet** [comment]
Cool！

Recent use，加上单位说明：（KB/s），放在左边的表格里。
就OK了

**Comment by xxnet** [comment]
已发布 
https://github.com/XX-net/XX-Net/issues/7875

感谢付出！
