### ISSUE TITLE
[任务] 升级后，删除老版本

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#72]
### 问题：
解压后，再加上生成的pyc文件， 一个版本的文件已经达到50M左右。
特别是最近升级很多，是要删除老版本了。

### 方案：
启动时，扫描code目录，删除非当前版本的子目录。

### 任务说明：
* 难度： 1星
* 技能需求：python

**Comment by onplus** [comment]
我自己是保留两三个版本的。

不能自动删除全部非当前版本，如果新版本不能用，回退就不方便。

默认保留N个版本 或者在这儿加个select

- 保留全部版本
- 保留default，stable和test
- 保留使用的版本

![image](https://user-images.githubusercontent.com/31188782/32170095-2954fd16-bdae-11e7-9766-7cf889464e94.png)

**Comment by SeaHOH** [comment]
建议稳定版和测试版都保留最近两个版本，升级时标注旧版本类型即可分辨。

**Comment by xxnet** [comment]
​好的，onplus 的建议不错，加个select。
那么默认是哪个？

切换版本还是有些人的。

要不要给一个切换版本的功能？

**Comment by MySource14** [comment]
最好能保留切换版本的功能，稳定版、测试版最好也保留一个备份：就是说保留一个测试版，两个稳定版。

**Comment by xxnet** [comment]
大家在原目录下切换版本的多不多？

可以去用户里调查一下

**Comment by xxnet** [comment]
简单化，就分为两类用户： 傻瓜用户和高级用户。
* 傻瓜用户
  只需要保留当前版本。
* 高级用户
  列出所有的版本
   手动删除旧版本
  也可以切换不同版本。

大家觉得怎样？

**Comment by SeaHOH** [comment]
普通的，只保留当前版本。

折腾的，保留所有版本，启动时和 UI 提示现有有多少个版本。

是不是更简单？

**Comment by xxnet** [comment]
​用户自己切换到”折腾“模式后，就不提示了，用户自己去系统菜单里管理就好。
怎样？

**Comment by SeaHOH** [comment]
尽量简化，这个就没必要整 UI 来切换版本，手动很简单。
然后提示折腾的用户现有多少个版本不就好了，实现起来也不麻烦。

**Comment by MeABc** [comment]
不知道在哪发这个，在这里强行插入 :）

各位能不能搞个目录结构啊，像我这样的新人小白光看到任务但找不到方向啊----不知道在哪改啊，虽说找找也是可以的，但新人入门难啊。

**Comment by MeABc** [comment]
这里的新人不一定是技术上的，更多还是指对这个项目了解这方面的。

**Comment by MeABc** [comment]
既然 X 大有意搞成团队型，那这方面的工作还是必不可少的。

**Comment by MeABc** [comment]
issues 不能置顶，放在一个文件里，然后在 readme 提醒一下如何？

**Comment by onplus** [comment]
@MeABc 
虽然不是最新版本的目录结构
https://github.com/XX-net/XX-Net/wiki/技术说明

**Comment by MeABc** [comment]
@onplus 谢谢！

**Comment by onplus** [comment]
@MeABc  可以装个插件Octotree https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc

**Comment by MeABc** [comment]
@onplus  哇，非常感谢！

**Comment by xxnet** [comment]
第一个版本，先做成最简单的模式：

版本升级管理，下面新增一个select ：
   只保留最新版本（默认）
   保留所有版本

系统启动时，如果只保留最新版本，检测到旧版本目录，删除旧版本。

----------------------------------------
这里，如果不提示，会不会一些希望保留旧版本的人有意见？
要不要在 WebUI上，提示”发现旧版本，是否删除？“

**Comment by dou4cc** [comment]
@xxnet 你怎么那么喜欢简单问题复杂化？可以在data里搞一个update-config.conf来保存升级设置，旧版升上来的没这个文件，代表保留所有旧版；全新下载的有这个文件，代表不留旧版。

**Comment by dou4cc** [comment]
@xxnet 版本号的目的就是简化升级流程。你看很多大型商业软件，尤其是按所选功能付费的那种都没有版本号这个概念。
我个人觉得你所谓“最简单的模式”已经过于复杂。

**Comment by xxnet** [comment]
​
10月份发布了10个版本以上，新发布的删除旧版本功能，结果这些用户还不会自动删除这些文件？没有帮用户解决问题啊。

其实找回旧版也容易，重新下载就好了。
所以可以直接发布一个默认删除旧版的，少量用户收影响的，自己去重新下载老版本就OK了。

**Comment by wooowooo** [comment]
写了一些代码。可设置保留旧版本的数量。ui还没做

https://github.com/XX-net/XX-Net/compare/master...wooowooo:del-uneed

**Comment by xxnet** [comment]
​看了代码，建议代码尽量放在 update_from_github一个文件内，start.py去调用。
另外，为何要删除 模块代码？
  还没有节约到这个程度吧。

gae_server 的代码，如果删除了，确实可以节约不少空间，可是如果用户要用了，怎么提示？

**Comment by wooowooo** [comment]
删除模块的我只是先写出来，ui先不做

在设置删除的ui上用红色提示用户 确认不用后再启用 ，这样可以了吗？

**Comment by xxnet** [comment]
​还是不要让用户去删除模块了，UI上，用户会乱点。
目前没有必要删除模块。

**Comment by wooowooo** [comment]
ok,不放删除模块的ui。

windows的启动脚本需要改一改，支持使用系统python。
要不要写一个依赖的python库列表（及版本），给自己装python的用户看？（我对 
python不太熟悉）

**Comment by xxnet** [comment]
​使用系统的python，这样的用户太少，而且也没有带来好处。
就先不用做了。

**Comment by xxnet** [comment]
已完成，谢谢 @wooowooo
