### ISSUE TITLE
[任务] 开发issues 巡查机器人

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#74]
### 问题：
最近老是有人来发垃圾帖子。

### 方案：
使用github api
 https://developer.github.com/v3/issues/

巡查新开的issues，发现关键词，自动关闭
这里有一个例子，是关闭过期的讨论的：
https://github.com/bstriner/github-bot-close-inactive-issues

### 任务说明：
* 难度: 2星
* 技能需求： python
* 把代码调试好了，我来部署

**Comment by dou4cc** [comment]
不用api v4是怕赵克伯格耍流氓吗？

**Comment by xxnet** [comment]
​https://developer.github.com/v3/activity/events/types/#issuesevent
可以通过这个获得通知，不需要轮询

**Comment by xxnet** [comment]
任务完成
