### ISSUE TITLE
[任务] GAE 扫描线程设置太大时，提示用户

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net-dev#77]
### 讨论见这里：
https://github.com/XX-net/XX-Net/issues/8391

前面还有用户把扫描线程开到1000，把路由器搞死了，结果怀疑被墙检测出来封网络了。

### 改进方案：
  设置扫描线程的WebUI上，检查线程数，超过200时，拒绝并提示。
  提示里，带上Wiki 对扫描线程数的说明链接。

### 任务说明：
* 技能要求： js
* 难度： 2星

@wooowooo 你的强项

**Comment by wooowooo** [comment]
![default](https://user-images.githubusercontent.com/12052610/32931815-3ccb543e-cba1-11e7-90d6-8bc32a2dc81f.png)

输入大于200会直接改为200
没有做提示

https://github.com/XX-net/XX-Net/compare/master...wooowooo:max200?expand=1

**Comment by xxnet** [comment]
​再加个提示就好了，tip(。。。)

**Comment by wooowooo** [comment]
那没用,会马上被保存成功的tip覆盖

**Comment by dou4cc** [comment]
善用MDN：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/number#%E6%8C%87%E5%AE%9A_%E6%9C%80%E5%B0%8F%E6%9C%80%E5%A4%A7_%E5%80%BC

**Comment by SeaHOH** [comment]
不在网页端处理，tip 显示在服务端处理后返回的信息即可。

**Comment by xxnet** [comment]
​<input type="number" placeholder="multiple of 10" step="10" min="0" max="
200">
dou4cc给的方法不错。

还有一个方法，在用户修改数字时，立即检查并给出提示，不用等到点击提交时才处理。

**Comment by wooowooo** [comment]
修改了:
![default](https://user-images.githubusercontent.com/12052610/32980161-9ca35892-cc9c-11e7-9228-d81885e19f78.png)

这样不错，浏览器自动有颜色和文字提示。

`step="5"`  这虽然能让调整方便，不过也变成了强制5的倍数。

--------------

@dou4cc <<---- 发现一个高手
以后这种应该由你来做呀

**Comment by xxnet** [comment]
好棒

**Comment by xxnet** [comment]
已经合并
