### ISSUE TITLE
问一下X大是如何处理herokuapp的Free Dyno hours的

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#79]
@xxnet

**Comment by xxnet** [comment]
如果自己一个人用，free dyno 是足够的。

不够的话，填入信用卡信息，就够了

**Comment by dou4cc** [comment]
@xxnet 你填了吗？填的是自己的吗？能保证你的匿名性吗？

**Comment by onplus** [comment]
550个小时还不够个人用吗？
多弄几个邮箱注册小号

**Comment by dou4cc** [comment]
@onplus dyno不是每30天刷新一次，不管我什么时候建app、deploy，550hr都是每月初给我。

**Comment by xxnet** [comment]
​网上找一个卡号，因为不扣费的

**Comment by dou4cc** [comment]
@xxnet you sure?
![default](https://user-images.githubusercontent.com/7764678/33795485-223e9e0e-dd1d-11e7-8b06-bea82534d3b3.jpg)
