### ISSUE TITLE
话说3.x版本中Switchy Omega的配置文件不见了

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net-dev#8]
每次我帮别人配置的时候都得在GitHub上翻2.x的源代码, 然后找对应的配置文件.

好! 麻! 烦!~
和WiKi说的一点不一样!!

**Comment by yfdyh000** [comment]
XX-Net\code\default\SwitchyOmega\OmegaOptions.bak 吗？

**Comment by zjhzxhz** [comment]
喔~~ Here it is!

**Comment by xxnet** [comment]
​被挪到code/default 里了
下次提交把它挪出来

**Comment by zjhzxhz** [comment]
看到了~~
谢谢X大~
