### ISSUE TITLE
减小体积的建议

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net-dev#80]
xx-net要进入嵌入式平台，我来挖点坑。

### 分离部署appid功能

gae server版 6M。  部署功能可以做成云服务，由X大部署。

### 自动删除不用的平台代码

如果暂时不能做成运行时自动根据平台下载对应依赖，让用户设置哪个平台不用，自动删掉那部分文件也不错。

### `python27/`

最大就是这个了。因为我不写python， 我不清楚里面都是什么。linux和mac默认带有的标准库，如果没修改过，应该不要放进来。改过的应该改个名字

**Comment by xxnet** [comment]
1. ​部署模块，做成云服务，同时保留一个本地版本，给需要的人用。
   这个有考虑过，需要对GAE SDK 进行整改，避免多人操作时，互相干扰。

2. 自动删除不用的代码
   这个不难，Xndroid 已经这么干了

3. python27 放了各种库，特别是给Windows 准备了python 运行时。
  暂时为了傻瓜化。
  如果能够写一个 vbs 在Windows下第一次启动时，下载一个python运行时，也是不错的方案。


  里面还有linux/win32/mac 平台相关的库，用户不需要再下载。
     其中OpenSSL 库是主要的。
     如果能够做成按需下载，就可以更小。

  其中noarch 是自定义的库，这是公用库。
