### ISSUE TITLE
X-tunnel与自己创建域名+cloudflare的问题

### ISSUE THREAD

**Issue by lgh06** [XX-net/XX-Net-dev#82]
看起来X-tunnel是你们注册好了域名，加好了CDN，通过cdn访问appengine……   
  
那么，我自己已经给appengine套上域名也套上了cloudflare，现在地址栏里不加代理可以访问到我的appengine。  

XX-net有没有可以直接指定域名的功能，或者哪个老版本的goagent/goproxy能指定一个域名（而不是配置appid与google的可用ip）……  

或者哪位大神来告诉告诉我你们的项目结构…… 改哪些个文件…… 写过java js nodejs，看py和go依然是云里雾里……

**Comment by xxnet** [comment]
套上cloudflare 之后，ip和证书就是cloudflare的了。
  可以用上 code/defalut/x_tunnel/local/cloudflare_front的front。

然后是GAE的协议打包部分，需要用 code/defalut/gae_proxy/local/里的代码进行处理。
  需要把 gae_handler里面的 request_gae_server 函数进行修改，调用上面 cloudflare的部分。
改动也不算很大，但是需要处理好细节，对python不熟悉，估计会遇到不少困难。

喜欢折腾可以研究下，不想折腾，用teredo还简单些。

**Comment by lgh06** [comment]
OK.thx. I'll try.
