### ISSUE TITLE
关于智能路由使用IPV6直连

### ISSUE THREAD

**Issue by XndroidDev** [XX-net/XX-Net-dev#83]
不清楚智能路由中是否有使用IPV6直连的计划.
大部分被墙的网站都支持IPV6访问, 只不过通过teredo连接的IPV6, 系统通常不会主动去使用ipv6, 即使windows上可以修改注册项部分达到目的, 但实际用起来并不方便.
而XX-Net在收到代理请求后, 可以自己去查询AAAA记录并保存起来, 下次访问该域名可以直接使用上次查到的ipv6地址直连, 大大降低使用代理的延迟, 也可以解决大部分证书问题,
@xxnet

**Comment by xxnet** [comment]
​智能路由里，如果是黑名单中的域名，会采用远程DNS解析，就会很大可能解析到IPv6地址。

接下来是规则里，没有优先走IPv6，而是优先走GAE-》X-tunnel->Direct
原来如果直接走IPv4直连，有时确实能通，但是比GAE慢，如果走IPv6，应该会快一些。
这个是需要再进一步优化了

**Comment by XndroidDev** [comment]
在测试中并没有观察到 google等域名通过ipv6直连, 可能DNS解析还要很大改进.
另外鉴于目前ipv6并没有受到多大干扰, 通过ipv6使用国外DNS服务器查询即可, 可无需远程解析, 减小对服务器的依赖

**Comment by xxnet** [comment]
​是的，需要改代码
