### ISSUE TITLE
我想在 XX-Net 的 Wiki 里新建一页介绍一下华人圈

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#85]
目前我所知道的面向初次翻墙者的导航站只有[翻墙后](https://fanqianghou.com)。它推荐的媒体，要么有资本支持，要么是政治类的，不中立，不透明，不能让读者摆脱对局域网的依赖。鉴于中共在墙外SNS投入越来越多的水军，新人越来越难找到中文圈，中文圈越来越小，我想在wiki里按如下原则收集链接：
- 不限于被墙的站点。中文圈没被墙的漏网之鱼内容很碎，不翻墙的人不大关注。
- 避开有资本支持、高度中心化的站点。
- 避开只讨论政治的站点。
- 着重收集信息量大、偏技术类的站点。

**Comment by dou4cc** [comment]
@xx-Chen 活跃的开发者就你没关注这个repo，所以at一下。

**Comment by xx-Chen** [comment]
@dou4cc watch了。

**Comment by dou4cc** [comment]
打了个草稿：https://github.com/XX-net/XX-Net/wiki/%E4%B8%AD%E6%96%87%E5%9C%88%E5%AF%BC%E8%88%AA

有空再继续。

**Comment by Shell1688** [comment]
这想法很好！

**Comment by xxnet** [comment]
wiki上，请附上前面提到的收录原则

**Comment by dou4cc** [comment]
@onplus 

看到你加的 Toyo 里附上的 Telegram 链接使用了 t.me 而非 telegram.me，我改成了后者，觉得后者更正式，没有被其他人抢走的风险。

另外你应该注意到我添加链接时有意偏向开放的平台，比如尽可能提供 Mastodon 链接，即使没有内容，相应地不给出信息量小的知乎链接。Telegram 作为现代 IM ，使用中心化架构、强制上交手机号、有意限制端到端加密的应用场景，还[主动审查言论](https://www.solidot.org/story?sid=46222)、[对俄罗斯一套](https://twitter.com/durov/status/986361756351172608)[对硅谷一套](https://www.solidot.org/story?sid=54629)、至今[没有好好国际化](https://twitter.com/hjc4869/status/850783605819269120)。鉴于从逗比根据地找到其 Telegram 聊天室链接之容易，我建议移除其 Telegram 链接。

**Comment by dou4cc** [comment]
九条凛[复活了](https://twitter.com/dou4cc/status/1005425460715687938), 因为明显已被控制, 已从 wiki 移除.

**Comment by dou4cc** [comment]
暂时移除阮一峰, 他最近割韭菜太明显.

**Comment by dou4cc** [comment]
baskice 最近也割韭菜, 大家有看法吗?

**Comment by dou4cc** [comment]
因为[阮一峰同 easylist 的对抗](https://archive.is/8HBTJ), 我不再考虑将他加回去.

**Comment by onplus** [comment]
收录方法过于主观，建议移除或 “华语圈导航”改名

**Comment by dou4cc** [comment]
@onplus 你去改啊.

**Comment by dou4cc** [comment]
@onplus 中文改成华语是出于中立考虑.

**Comment by MeABc** [comment]
`
因为阮一峰同 easylist 的对抗, 我不再考虑将他加回去.
`

> 收录方法过于主观，建议移除或 “华语圈导航”改名

赞同！做为曾经的小站长，[阮一峰同 easylist 的对抗](https://archive.is/8HBTJ) 这个言论没有看出什么毛病！

**Comment by dou4cc** [comment]
移除了 Baskice, 因为 ta 不但割韭菜, 还停止了所有墙外社交活动.

**Comment by dou4cc** [comment]
@MeABc 阮一峰说 easylist 强奸他. 但事实是, easylist 是用户用广告拦截器主动订阅的, easylist 的维护者只是按照既定准则帮用户移除广告, 对抗 easylist 就是强奸用户.

**Comment by dou4cc** [comment]
有没有必要补充各人简介?

**Comment by lupus721** [comment]
https://doub.io 这个域名已经过期开始出售了，应该是废了

**Comment by dou4cc** [comment]
已撤回 @njingsb 的删除.

**Comment by dou4cc** [comment]
依当事人意愿移除了 PeterCxy: https://web.archive.org/web/20190523093133/https://github.com/njingsb.atom

**Comment by AnyWAT** [comment]
👇
虽然我不随便拉黑好友
但这次忍不住要说一下你
（未经同意）不要到处贴别人的资料
明白了吧
👍

**Comment by dou4cc** [comment]
因墙外人格分离, SerCom_KC已移除

SerCom_KC (2010.5.20 - 2019.8.2)

**Comment by dou4cc** [comment]
照例移除chengr28

**Comment by dou4cc** [comment]
因引流微博移除王垠

**Comment by lilydjwg** [comment]
请移除我的非网络用名和生活博客链接。

**Comment by SeaHOH** [comment]
果然大家只是不知道有这么个小本本(?)，知道后都会有点想法。
收集有用的部分就足够了，非要费尽心思的关联分散的信息，我实在是想不出“人肉”以外的词语来形容这种行为。

**Comment by dou4cc** [comment]
@lilydjwg 

> 请移除我的非网络用名和生活博客链接。

done

**Comment by SeaHOH** [comment]
还是把当事人叫来自己看吧，不知道还有多少人能回应。
我也没仔细看，只是单纯 @ 其中匹配到的本站用户，具体内容请大家自行检查，看能否接受。
@chenshaoju
@cloudwu
@chloerei
@FiveYellowMice
@audreyt
@lilydjwg
@klzgrad
@sumhat
@ayanamist
@programthink
@BYVoid
@oasisfeng
@zooxyt
@be5invis
@leask
@alsotang
@barretlee
@KenOokamiHoro
@yyx990803
@bobzhang
@GeeLaw
@donho
@bhuztez
@MarisaKirisame
@delphij
@lianghai
@manateelazycat
@zhangyubaka
@ice1000
@iovxw
@typcn
@mariotaku
@printempw
@heiher
@PCMan
@breakwa11

**Comment by ice1000** [comment]
希望能去掉我的中文三个汉字的名字

**Comment by printempw** [comment]
请更新我的昵称部分，仅保留 printempw 与 PRIN，多谢。

**Comment by be5invis** [comment]
Please remove my entry.
请移除我的条目。

**Comment by dou4cc** [comment]
共产党人不屑于隐瞒自己...

**Comment by chenshaoju** [comment]
我个人无所谓，估计有关部门早就给我建档了。

不过原则上还是经过别人同意吧。

**Comment by onplus** [comment]
https://github.com/onplus/XX-Net_Wiki/commits?author=dou4cc

**Comment by dou4cc** [comment]
@onplus 

你是指?

**Comment by dou4cc** [comment]
@onplus

??
```xml
  <entry>
    <id>tag:github.com,2008:CreateEvent/10621349116</id>
    <published>2019-10-14T02:40:35Z</published>
    <updated>2019-10-14T02:40:35Z</updated>
    <link type="text/html" rel="alternate" href="https://github.com/onfork/XX-Net_Wiki//"/>
    <title type="html">onplus created a repository onfork/XX-Net_Wiki</title>
    <author>
      <name>onplus</name>
      <uri>https://github.com/onplus</uri>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars0.githubusercontent.com/u/31188782?s=30&amp;v=4"/>
    <content type="html">&lt;div class=&quot;repo&quot;&gt;&lt;div class=&quot;body&quot;&gt;
&lt;!-- create --&gt;
&lt;div class=&quot;d-flex flex-items-baseline border-bottom border-gray py-3&quot;&gt;
    &lt;span class=&quot;mr-3&quot;&gt;&lt;a class=&quot;d-inline-block&quot; href=&quot;/onplus&quot; rel=&quot;noreferrer&quot;&gt;&lt;img class=&quot;avatar&quot; src=&quot;https://avatars3.githubusercontent.com/u/31188782?s=64&amp;amp;v=4&quot; width=&quot;32&quot; height=&quot;32&quot; alt=&quot;@onplus&quot;&gt;&lt;/a&gt;&lt;/span&gt;
  &lt;div class=&quot;d-flex flex-column width-full&quot;&gt;
        &lt;div class=&quot;d-flex flex-items-baseline&quot;&gt;
          &lt;div&gt;
            &lt;a class=&quot;link-gray-dark no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/onplus&quot; rel=&quot;noreferrer&quot;&gt;onplus&lt;/a&gt;
            
            created a
            repository
            
            &lt;a class=&quot;link-gray-dark no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/onfork/XX-Net_Wiki&quot; rel=&quot;noreferrer&quot;&gt;onfork/XX-Net_Wiki&lt;/a&gt;
            &lt;span class=&quot;f6 text-gray-light no-wrap ml-1&quot;&gt;
              &lt;relative-time datetime=&quot;2019-10-14T02:40:35Z&quot; class=&quot;no-wrap&quot;&gt;Oct 14, 2019&lt;/relative-time&gt;
            &lt;/span&gt;
          &lt;/div&gt;
        &lt;/div&gt;

    &lt;div class=&quot;Box p-3 mt-2&quot;&gt;
      &lt;div&gt;
        &lt;div class=&quot;f4 lh-condensed text-bold text-gray-dark&quot;&gt;
            &lt;a class=&quot;link-gray-dark no-underline text-bold wb-break-all d-inline-block&quot; href=&quot;/onfork/XX-Net_Wiki&quot; rel=&quot;noreferrer&quot;&gt;onfork/XX-Net_Wiki&lt;/a&gt;
        &lt;/div&gt;


          &lt;p class=&quot;f6 text-gray mt-2 mb-0&quot;&gt;
            &lt;span&gt;Updated Oct 14&lt;/span&gt;
          &lt;/p&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;/div&gt;</content>
  </entry>
```

**Comment by heiher** [comment]
Please remove my entry.
请移除我的条目。

**Comment by yeahwu** [comment]
哎哟，这个项目居然有个小本本，有关部门表示非常重视！一窝端进行中……😂😂

**Comment by mariotaku** [comment]
不得不指出，那份ID列表里，一些人是
* （疑似）被喝了茶的
* 已经不在世的

我个人对GitHub上任何类“awesome-xxx”的汇总类项目很反感，尤其是把很多人@ 进来。除了泄露我个人隐私的内容，我不会在乎是否有人把我ID放进去，只是我认为这没什么意义。

**Comment by SeaHOH** [comment]
> 我个人对GitHub上任何类“awesome-xxx”的汇总类项目很反感，尤其是把很多人@ 进来。除了泄露我个人隐私的内容，我不会在乎是否有人把我ID放进去，只是我认为这没什么意义。

就因为他在扒隐私，所以才 @ 你们以知悉。虽然现在没包含部分人的隐私，但以后可不一定。

我不是仓库所有者，没法直接处理，只好 @ 大家了，如有打扰，还请见谅。

其实以前我都是不在乎的，直到前几天，突然觉得他这个行为实在是不好，所以才想看看被影响的本人是个什么意见。

**Comment by AnyWAT** [comment]
@dou4cc 有情况？原来每天定时更新的 https://github.com/CNMan/dnscrypt-proxy-config 已停止5天了：CNMan Tue 15 Oct 2019 12:05:05 AM UTC 处的 ID链接也已失效

**Comment by dou4cc** [comment]
因恶意引流/选择性陈述, 移除陈少举

- https://archive.ph/YZ2j7
- https://archive.ph/YI4IR
- https://archive.ph/CdJlA

**Comment by GeeLaw** [comment]
请把我从列表里删除。

**Comment by dou4cc** [comment]
> 请把我从列表里删除。

**Comment by dou4cc** [comment]
移除过气网红bhuztez/marisa/ice1000
欢迎重新加入

**Comment by mariotaku** [comment]
当时没去看到底写的什么，现在发现里面连生日都要记载，为什么？请删除我的条目。

**Comment by SeaHOH** [comment]
> 当时没去看到底写的什么，现在发现里面连生日都要记载，为什么？请删除我的条目。

你也太迟钝了，都给你说他在扒隐私，还不信。虽然部分人自身有保护意识，没暴露什么有用的信息，但是他一旦扒到就会记录保存。

**Comment by SeaHOH** [comment]
@xxnet 鉴于这个项目的特殊性，你是不是需要规范 @dou4cc 的行为，定下底线？

**Comment by mariotaku** [comment]
> > 当时没去看到底写的什么，现在发现里面连生日都要记载，为什么？请删除我的条目。
> 
> 你也太迟钝了，都给你说他在扒隐私，还不信。虽然部分人自身有保护意识，没暴露什么有用的信息，但是他一旦扒到就会记录保存。

我当时觉得这种整合很蠢就看都没看，今天好奇打开发现比我想象中还要蠢……

**Comment by SeaHOH** [comment]
> 我当时觉得这种整合很蠢就看都没看，今天好奇打开发现比我想象中还要蠢……

你上次的回复可能误导了后来的人，之前都有人要求删除或修改，但是你回复后就没有了。

**Comment by xxnet** [comment]
还是删除了吧，这种行为如果操作不好就是好事变坏事。

**Comment by dou4cc** [comment]
先放我gist: https://gist.github.com/dou4cc/d843edff2a8d074d51d1212fc7b2fc61

**Comment by Showfom** [comment]
麻烦把我的 ID 从列表里删除，谢谢

**Comment by dou4cc** [comment]
@Showfom 

https://staltz.com/open-source-without-maintainers.html

**Comment by SeaHOH** [comment]
之前有人自己删掉，你又添加回去，现在这样表态有意思么？

**Comment by mariotaku** [comment]
已经report for abuse上面的那个gist snippet。请 @dou4cc 尊重所有列表中的人自己决定信息在哪里出现，以及被遗忘的权利。

**Comment by xxnet** [comment]
wiki上的列表我已经删除了，还有哪个地方有列表吗？

**Comment by SeaHOH** [comment]
哦，真删了。github 只推送了修改的消息，删除的没看到。
他自己的 gist 倒是没必要在意，除非有记录更详细的隐私。

**Comment by dou4cc** [comment]
@SeaHOH 

> 之前有人自己删掉，你又添加回去

他删的是整个页面

**Comment by SeaHOH** [comment]
> 他删的是整个页面

是嘛，只看到你们来回改，没注意具体内容。我觉得根源还是你与大家三观差异太大，真的不认为自己的做法有问题吗？

**Comment by dou4cc** [comment]
@SeaHOH

> 真的不认为自己的做法有问题吗？

气哭了

**Comment by xxnet** [comment]
做好事并不容易，需要考虑政治、伦理、以及各种现实问题。
多看看多学习，慢慢来。

**Comment by dou4cc** [comment]
(点头)

(假装自己是萌新)
