### ISSUE TITLE
能不能想办法把X-Tunnel的成本降到0？

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net-dev#87]
最近有点懒，不想自己准备梯子了，开始打XX-Net的主意。
X-Tunnel的前端主要是GAE和CDN，GAE应该是能直接作为Psiphon3前置的，CDN接一个Heroku也就能给Psiphon3做前置了，这样搞下来不需要租VPS，还有Psiphon那帮人帮你换IP防止被识别成代理。Psiphon3开源在Bitbucket。

**Comment by xxnet** [comment]
X-Tunnel的定位，是给XX-Net持续开发改进提供资金支持，同时给用户提供更加方便、有效的上网方式。
很多非技术用户，自己注册个GAE appid都不会啊。

GAE_proxy 是免费的，只是GAE有一些限制，比如不支持WebSocket。

喜欢折腾的，最简单的方式是直接heroku shadowsocks，一个工具搞定。
个人用流量不大，是可行的。

**Comment by dou4cc** [comment]
> 给XX-Net持续开发改进提供资金支持

所以能提现而不影响你匿名了吗？

--------

> 最简单的方式是直接heroku shadowsocks

直连速度不忍直视。找跳板、搭CDN很费精力。

**Comment by onplus** [comment]
能啊，让vultr赞助几十台独服
