### ISSUE TITLE
win10 不会自动安装证书

### ISSUE THREAD

**Issue by wpyok500** [XX-net/XX-Net-dev#9]
May 07 18:56:02.886 - [INFO] SSL use version:TLSv1_2
May 07 18:56:03.589 - [INFO] OpenSSL support alpn
May 07 18:56:03.605 - [INFO] load ip range file:D:\Program Files\XX-Net\code\default\gae_proxy\local\ip_range.txt
May 07 18:56:03.620 - [INFO] detected Win10, enable connect concurrency control, interval:40
May 07 18:56:03.636 - [INFO] load google ip_list num:0, gws num:0
May 07 18:56:03.651 - [INFO] OpenSSL support alpn
May 07 18:56:03.683 - [DEBUG] ## GAEProxy set keep_running: True
May 07 18:56:03.683 - [INFO] ------------------------------------------------------
May 07 18:56:03.683 - [INFO] Python Version : 2.7.11
May 07 18:56:03.683 - [INFO] OS : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
May 07 18:56:03.683 - [INFO] Listen Address : 127.0.0.1:8087
May 07 18:56:03.683 - [INFO] GAE APPID :
May 07 18:56:03.683 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
May 07 18:56:03.683 - [INFO] ------------------------------------------------------
May 07 18:56:03.683 - [INFO] no CA file exist
May 07 18:56:03.683 - [INFO] clean old site certs
May 07 18:56:03.698 - [INFO] generate CA file:D:\Program Files\XX-Net\data\gae_proxy\CA.crt
May 07 18:56:04.089 - [INFO] create CA
May 07 18:56:04.980 - [DEBUG] network is ok, cost:2860 ms
May 07 18:56:05.377 - [INFO] PAC from:127.0.0.1:62638 GET /proxy.pac
May 07 18:56:05.389 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('D:\Program Files\XX-Net\data\gae_proxy\proxy.pac')
May 07 18:56:05.425 - [INFO] PAC from:127.0.0.1:62641 GET /proxy.pac
May 07 18:56:05.429 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('D:\Program Files\XX-Net\data\gae_proxy\proxy.pac')
May 07 18:56:07.706 - [INFO] PAC from:127.0.0.1:62638 GET /proxy.pac
May 07 18:56:07.736 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('D:\Program Files\XX-Net\data\gae_proxy\proxy.pac')
May 07 18:56:07.990 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
May 07 18:56:07.991 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
May 07 18:56:07.992 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
May 07 18:56:08.585 - [INFO] PAC from:127.0.0.1:62703 GET /proxy.pac
May 07 18:56:08.592 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('D:\Program Files\XX-Net\data\gae_proxy\proxy.pac')
May 07 18:56:08.619 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
May 07 18:56:09.331 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
May 07 18:56:09.347 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=ee02263a-40c2-4ae8-a97a-d6ad3b6793bd&version=3.1.6&platform=Windows-10-10.0.10586
May 07 18:56:11.274 - [INFO] scan_ip add ip:103.1.139.152 time:545
May 07 18:56:11.552 - [DEBUG] get ip:103.1.139.152 t:545
May 07 18:56:15.516 - [DEBUG] create_ssl update ip:103.1.139.152 time:536 h2:1

**Comment by wpyok500** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 QQBrowser/9.3.6874.400
xxnet-version: 3.1.6

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:10 good:9
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:1
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
connected-link: new:0 used:0

链接都没有

**Comment by xxnet** [comment]
​新的策略，需要时才创建link
worker: h1:0 h2:1
 有worker，就可以了

**Comment by wpyok500** [comment]
@jzp820927  完全新装(从网页下载不是从xx的web页下载)才要开始扫ip，不是升级安装(重来不升级安装)旧good_id没复制进去，当然一个ip都没有，一运行就复制贴出日志。
@xxnet CA.crt证书没自动装，不能访问googgle
