### ISSUE TITLE
提供使用ip切换？

### ISSUE THREAD

**Issue by inksnw** [XX-net/XX-Net-dev#91]
公司和家里扫出的ip因为网络环境问题不能通用，每次切换了就要重新扫描，能不能保存下，可选手动切换？

**Comment by dou4cc** [comment]
有了版本切换还要配置切换。。

**Comment by SeaHOH** [comment]
自己改下文件名很难么？

**Comment by inksnw** [comment]
@SeaHOH 不难啊,只是建议下嘛,

**Comment by dou4cc** [comment]
建议 XX-Net 出操作系统。

**Comment by xxnet** [comment]
推荐的方式是建两个不同的xx-net目录，不同网络环境下启动不同的目录

**Comment by xxnet** [comment]
​因为没有很好的自动检测网络变化的手段，否则做一个自动切换ip库也不难。
手机上会好一点，Android 会提供通知。

**Comment by SeaHOH** [comment]
只需定时检测出口 IP 就行，不过这样真的好吗？

**Comment by dou4cc-witness** [comment]
我被楼主拉黑了。

----------

> 只需定时检测出口 IP 就行

不行。

**Comment by dou4cc-witness** [comment]
楼主你面对的问题比你以为的复杂。你以为你公司是一个环境，家里是另一个，这只是你的认为。实际上即使一直待在家里，工作日、周末可能都不是一种环境，白天和晚上也不同，这种事情和出口 IP 没有半毛钱关系。当你意识到你的网络环境变了，你已经完了，学习好的配置已经乱掉了。

**Comment by SeaHOH** [comment]
太夸张了吧。。。
出口 IP 并不是说区分单个 IP，而是看 IP 所属网络，而且单个网络的变化不会有这么频繁。

**Comment by xxnet** [comment]
​大家讨论时，应该多列举事实证据。少用夸张的说法。

**Comment by dou4cc-witness** [comment]
@SeaHOH 请给出具体方案来区分同一个市的电信公司网络和电信家庭网络。

**Comment by dou4cc-witness** [comment]
@SeaHOH 对于普遍使用流量穿透的宽带，如何定义“出口 IP”？

**Comment by dou4cc-witness** [comment]
就连楼主都没指望自动切换，所以我指出，发现网络环境变了时已经晚了。所以我们需要可以回滚的日志，以及从日志到翻墙配置的无状态映射。

**Comment by xxnet** [comment]
​我们考虑手机平台下，从wifi切换到移动网络，一方面可以测到网络切换的通知，可以通过检测出口ip的解析名来确认。

至于Ip不变，只是上午和晚上的差别，暂时也没有好的办法，就先不管。
对于网络出口，ip变化，检测出来的出口名称一般是一样的，可以。

**Comment by dou4cc-witness** [comment]
这样对前置代理不友好？要么把项目拆分？

**Comment by SeaHOH** [comment]
有必要么，这只适用于手机吧。
笔记本写个改文件名的小脚本就行了。

**Comment by dou4cc-witness** [comment]
有人对我提到的把状态提取出来以方便实验的做法感兴趣吗？

**Comment by SeaHOH** [comment]
跟我当时看 Golang 的库时是一个感觉。。。

**Comment by dou4cc-witness** [comment]
@SeaHOH 我是想借鉴 WebKit 的录制、回放。log 打全的话，从 log 生成翻墙策略的过程应该是可以重现的。这对 XX-Net 的模块化或也有好处。

**Comment by inksnw** [comment]
@dou4cc 哈,总觉得你这句操作系统在嘲讽我-_-,开玩笑啦
只是个小建议,对个人来说并不太需要这个功能,问问大家有没有需要的.
对我来说把xx-net改成python3,成为开发者的一员才是想做的-_-

**Comment by dou4cc** [comment]
@inksnw 就是在嘲讽你啊～话说如果 XX-Net 轻量一点的话也许已经有各种语言的 port 了。

**Comment by xxnet** [comment]
​python3 还可以再拖到年底再动手。

@inksnw
接下来动手做路由器的优化，可以看看这里
https://github.com/XX-net/XX-Net-dev/issues

看看有什么能帮上忙的
