### ISSUE TITLE
冒个泡,想问一下gae还能用吗?

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net-dev#93]
好不容易翻出来,由于自己的appid忘了,也不知道gae能不能用.好多生面孔.
gogotunnel是不是倒闭了?
lantern坟头草都丈高了,goproxy没影了.
这尼玛找不到组织了!
@xxnet @Cat7373 @xyuanmu

**Comment by Cat7373** [comment]
哟，都快把你忘了😂

**Comment by yeahwu** [comment]
@Cat7373 哦,被关在墙内了,汗! issues上也没看见以前那些老人了.

**Comment by dou4cc** [comment]
> 好不容易翻出来

GitHub 没被墙啊... 你在新疆?

**Comment by dou4cc** [comment]
号被盗了?

**Comment by yeahwu** [comment]
@dou4cc 在学校有时间有空间,出来被蹂躏一两次哪有闲心翻墙哪!
你看,应该和俺同期毕业的 @hzxie 不也没声了嘛!

**Comment by hzxie** [comment]
自从要开启IPv6之后我就弃坑转投Shadowsocks了. 主要是GAE没法访问Google Scholar.

**Comment by xxnet** [comment]
好久不见你 @yeahwu

**Comment by yeahwu** [comment]
@xxnet X大好久不见,gae下IPv4不能用了吗?
@hzxie 好久不见,记得以前Google Scholar是可以直连的吧.

**Comment by xxnet** [comment]
GAE ​IPv4 已经不能用了，据说绑定域名，挂CDN还能用

**Comment by Cat7373** [comment]
好像是这个理，IP 屏蔽，CDN 就不会被屏蔽了，然后域名也不能是 gae 的域名

**Comment by hzxie** [comment]
@yeahwu Google Scholar是可以连, 但是BibTeX不能用.
然后有时候还会被Google拦截说IP有异常流量.
